# Assignment - Practice Questions[100]

In [1]:
# Load the Excel file 'Ecommerce_Sales_Analysis.xlsx' (Data sheet) into a DataFrame called `df`.
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r"C:\Users\mingm\Videos\Ecommerce Sales Data.xlsx")

In [3]:
df.head()

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,2013,6/13/2013,6/17/2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,2012,2012-11-10 00:00:00,10/18/2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,2012,2012-11-10 00:00:00,10/18/2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
# Display the first 10 rows of the DataFrame.
df.head(10)

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,2013,6/13/2013,6/17/2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,2012,2012-11-10 00:00:00,10/18/2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,2012,2012-11-10 00:00:00,10/18/2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

In [5]:
# Display the last 7 rows of the DataFrame.
df.tail(7)

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9987,9988,CA-2014-163629,2014,11/18/2014,11/22/2014,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,...,30605,South,TEC-AC-10001539,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,79.990,1,0.0,28.7964
9988,9989,CA-2014-163629,2014,11/18/2014,11/22/2014,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.100,5,0.0,55.6470
9989,9990,CA-2011-110422,2011,1/22/2011,1/24/2011,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2014-121258,2014,2/27/2014,2014-04-03 00:00:00,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2014-121258,2014,2/27/2014,2014-04-03 00:00:00,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2014-121258,2014,2/27/2014,2014-04-03 00:00:00,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2014-119914,2014,2014-05-05 00:00:00,2014-10-05 00:00:00,Second Class,CC-12220,Chris Cortes,Consumer,United States,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [6]:
# Print the shape (rows, columns) of the DataFrame.
df.shape

(9994, 22)

In [7]:
# List all column names of the DataFrame.
df.columns

Index(['Row ID', 'Order ID', 'Year', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [8]:
# Check the data types of each column using `.dtypes`.
df.dtypes

Row ID             int64
Order ID             str
Year               int64
Order Date        object
Ship Date         object
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [9]:
# Get a concise summary of the DataFrame using `.info()`.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Year           9994 non-null   int64
 3   Order Date     9994 non-null   object
 4   Ship Date      9994 non-null   object
 5   Ship Mode      9994 non-null   str
 6   Customer ID    9994 non-null   str
 7   Customer Name  9994 non-null   str
 8   Segment        9994 non-null   str
 9   Country        9994 non-null   str
 10  City           9994 non-null   str
 11  State          9994 non-null   str
 12  Postal Code    9994 non-null   int64
 13  Region         9994 non-null   str
 14  Product ID     9994 non-null   str
 15  Category       9994 non-null   str
 16  Sub-Category   9994 non-null   str
 17  Product Name   9994 non-null   str
 18  Sales          9994 non-null   float64
 19  Quantity       9994 non-null   int64
 20  Discount       9994 non-null   float64
 21  Profit         9994 non-null   float64
dtypes: float64(3), int64(4), object(2), str(13)
memory usage: 1.7+ MB

In [10]:
# Generate descriptive statistics for all numeric columns.
df.describe()

,Row ID,Year,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2012.722934,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,1.124039,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,2011.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2012.000000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2013.000000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2014.000000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2014.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [11]:
# Count the total number of missing values in each column.
df.isnull().sum()

Row ID           0
Order ID         0
Year             0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [12]:
# Display a random sample of 15 rows from the DataFrame.
df.sample(15)

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1342,1343,CA-2014-113481,2014,2014-03-01 00:00:00,2014-05-01 00:00:00,First Class,AS-10045,Aaron Smayling,Corporate,United States,...,28540,South,OFF-BI-10000474,Office Supplies,Binders,Avery Recycled Flexi-View Covers for Binding S...,28.854,6,0.7,-21.1596
9284,9285,CA-2011-161032,2011,11/18/2011,11/23/2011,Standard Class,MK-17905,Michael Kennedy,Corporate,United States,...,53132,Central,FUR-CH-10001482,Furniture,Chairs,Office Star - Mesh Screen back chair with Viny...,392.940,3,0.0,43.2234
9217,9218,US-2014-118157,2014,11/15/2014,11/18/2014,First Class,AW-10930,Arthur Wiediger,Home Office,United States,...,55407,Central,OFF-EN-10004459,Office Supplies,Envelopes,Security-Tint Envelopes,15.280,2,0.0,7.4872
379,380,CA-2012-130792,2012,4/28/2012,2012-05-05 00:00:00,Standard Class,RA-19915,Russell Applegate,Consumer,United States,...,77095,Central,OFF-ST-10003327,Office Supplies,Storage,Akro-Mils 12-Gallon Tote,23.832,3,0.2,2.6811
4368,4369,CA-2014-117044,2014,2014-12-09 00:00:00,9/14/2014,Second Class,HA-14920,Helen Andreada,Consumer,United States,...,60623,Central,OFF-PA-10003657,Office Supplies,Paper,Xerox 1927,20.544,6,0.2,6.4200
9743,9744,CA-2013-137127,2013,6/17/2013,6/23/2013,Standard Class,JJ-15445,Jennifer Jackson,Consumer,United States,...,19711,East,OFF-LA-10001641,Office Supplies,Labels,Avery 518,9.450,3,0.0,4.5360
9928,9929,CA-2013-129630,2013,2013-05-09 00:00:00,2013-05-09 00:00:00,Same Day,IM-15055,Ionia McGrath,Consumer,United States,...,94122,West,FUR-FU-10000260,Furniture,Furnishings,"6"" Cubicle Wall Clock, Black",24.270,3,0.0,8.7372
6840,6841,CA-2012-166338,2012,2012-06-12 00:00:00,2012-07-12 00:00:00,First Class,MP-18175,Mike Pelletier,Home Office,United States,...,45373,East,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,14.832,3,0.7,-10.3824
4110,4111,CA-2012-153717,2012,12/25/2012,2013-01-01 00:00:00,Standard Class,DL-13495,Dionis Lloyd,Corporate,United States,...,48227,Central,FUR-BO-10004360,Furniture,Bookcases,Rush Hierlooms Collection Rich Wood Bookcases,160.980,1,0.0,20.9274
1093,1094,CA-2012-165085,2012,12/27/2012,12/31/2012,Standard Class,BT-11485,Brad Thomas,Home Office,United States,...,20735,East,OFF-PA-10000605,Office Supplies,Paper,Xerox 1950,28.900,5,0.0,14.1610
8297,8298,US-2012-158911,2012,2012-05-07 00:00:00,2012-11-07 00:00:00,Standard Class,RS-19765,Roland Schwarz,Corporate,United States,...,28205,South,FUR-FU-10003829,Furniture,Furnishings,Stackable Trays,4.928,2,0.2,0.7392
4415,4416,CA-2011-153983,2011,11/29/2011,2011-06-12 00:00:00,Standard Class,AH-10210,Alan Hwang,Consumer,United States,...,94122,West,TEC-PH-10004586,Technology,Phones,Wilson SignalBoost 841262 DB PRO Amplifier Kit,575.920,2,0.2,71.9900
2678,2679,US-2011-160780,2011,6/21/2011,6/21/2011,Same Day,SV-20785,Stewart Visinsky,Consumer,United States,...,81001,West,OFF-BI-10002931,Office Supplies,Binders,"Avery Trapezoid Extra Heavy Duty 4"" Binders",25.164,2,0.7,-16.7760
8255,8256,CA-2014-152310,2014,8/13/2014,8/20/2014,Standard Class,DK-12895,Dana Kaydos,Consumer,United States,...,98103,West,TEC-PH-10002538,Technology,Phones,Grandstream GXP1160 VoIP phone,242.624,8,0.2,27.2952
2062,2063,CA-2011-106439,2011,10/31/2011,2011-04-11 00:00:00,Standard Class,GG-14650,Greg Guthrie,Corporate,United States,...,90049,West,OFF-PA-10000477,Office Supplies,Paper,Xerox 1952,64.740,13,0.0,30.4278

# SELECTION

In [13]:
# Select only the 'Order ID', 'Customer Name', 'Sales', and 'Profit' columns.
df[['Order ID','Customer Name','Sales','Profit']]

            Order ID     Customer Name     Sales    Profit
0     CA-2013-152156       Claire Gute  261.9600   41.9136
1     CA-2013-152156       Claire Gute  731.9400  219.5820
2     CA-2013-138688   Darrin Van Huff   14.6200    6.8714
3     US-2012-108966    Sean O'Donnell  957.5775 -383.0310
4     US-2012-108966    Sean O'Donnell   22.3680    2.5164
...              ...               ...       ...       ...
9989  CA-2011-110422  Tom Boeckenhauer   25.2480    4.1028
9990  CA-2014-121258       Dave Brooks   91.9600   15.6332
9991  CA-2014-121258       Dave Brooks  258.5760   19.3932
9992  CA-2014-121258       Dave Brooks   29.6000   13.3200
9993  CA-2014-119914      Chris Cortes  243.1600   72.9480

[9994 rows x 4 columns]

In [14]:
# Select all rows where `Sales` is greater than 1000.
df[df['Sales'] > 1000]

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
10,11,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184,9,0.2,85.3092
24,25,CA-2012-106320,2012,9/25/2012,9/30/2012,Standard Class,EB-13870,Emily Burns,Consumer,United States,...,84057,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.630,3,0.0,240.2649
27,28,US-2012-150630,2012,9/17/2012,9/21/2012,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,...,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,7,0.5,-1665.0522
35,36,CA-2013-117590,2013,2013-09-12 00:00:00,2013-11-12 00:00:00,First Class,GH-14485,Gene Hale,Corporate,United States,...,75080,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544,7,0.2,123.4737
54,55,CA-2013-105816,2013,2013-12-12 00:00:00,12/18/2013,Standard Class,JM-15265,Janet Molinari,Corporate,United States,...,10024,East,TEC-PH-10002447,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.950,5,0.0,298.6855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9866,9867,US-2012-116981,2012,3/26/2012,3/28/2012,Second Class,SM-20950,Suzanne McNair,Corporate,United States,...,10009,East,OFF-ST-10002615,Office Supplies,Storage,"Dual Level, Single-Width Filing Carts",1085.420,7,0.0,282.2092
9925,9926,CA-2012-159534,2012,3/20/2012,3/23/2012,First Class,DH-13075,Dave Hallsten,Corporate,United States,...,10035,East,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,1087.936,8,0.2,353.5792
9929,9930,CA-2013-129630,2013,2013-05-09 00:00:00,2013-05-09 00:00:00,Same Day,IM-15055,Ionia McGrath,Consumer,United States,...,94122,West,TEC-CO-10003763,Technology,Copiers,Canon PC1060 Personal Laser Copier,2799.960,5,0.2,944.9865
9947,9948,CA-2014-121559,2014,2014-02-06 00:00:00,2014-04-06 00:00:00,Second Class,HW-14935,Helen Wasserman,Corporate,United States,...,46203,Central,FUR-CH-10003746,Furniture,Chairs,Hon 4070 Series Pagoda Round Back Stacking Chairs,1925.880,6,0.0,539.2464
9948,9949,CA-2014-121559,2014,2014-02-06 00:00:00,2014-04-06 00:00:00,Second Class,HW-14935,Helen Wasserman,Corporate,United States,...,46203,Central,OFF-AP-10002945,Office Supplies,Appliances,Honeywell Enviracaire Portable HEPA Air Cleane...,2405.200,8,0.0,793.7160

In [15]:
# Use `.loc[]` to select rows 100–120 and columns 'Category' to 'Sales'.
df.loc[100:120, 'Category':'Sales']

,Category,Sub-Category,Product Name,Sales
100,Technology,Accessories,SanDisk Ultra 64 GB MicroSDHC Class 10 Memory ...,95.976
101,Office Supplies,Binders,Avery Hidden Tab Dividers for Binding Systems,1.788
102,Office Supplies,Paper,Universal Premium White Copier/Laser Paper (20...,23.920
103,Technology,Accessories,Logitech K350 2.4Ghz Wireless Keyboard,238.896
104,Furniture,Furnishings,"Deflect-o DuraMat Lighweight, Studded, Beveled...",102.360
105,Office Supplies,Binders,"Avery Trapezoid Ring Binder, 3"" Capacity, Blac...",36.882
106,Technology,Accessories,Memorex Mini Travel Drive 8 GB USB 2.0 Flash D...,74.112
107,Technology,Phones,Speck Products Candyshell Flip Case,27.992
108,Office Supplies,Art,Newell Chalk Holder,3.304
109,Technology,Accessories,Logitech Gaming G510s - Keyboard,339.960
110,Furniture,Furnishings,Magnifier Swing Arm Lamp,41.960
111,Office Supplies,Art,"Hunt PowerHouse Electric Pencil Sharpener, Blue",75.960
112,Office Supplies,Binders,"Avery Durable Plastic 1"" Binders",27.240
113,Office Supplies,Fasteners,"OIC Colored Binder Clips, Assorted Sizes",40.096
114,Office Supplies,Envelopes,"Redi-Strip #10 Envelopes, 4 1/8 x 9 1/2",4.720
115,Office Supplies,Paper,Xerox 1921,23.976
116,Office Supplies,Envelopes,"Tyvek Top-Opening Peel & Seel Envelopes, Plain...",130.464
117,Furniture,Tables,Hon Racetrack Conference Tables,787.530
118,Office Supplies,Binders,GBC DocuBind 300 Electric Binding Machine,157.794
119,Furniture,Furnishings,Artistic Insta-Plaque,47.040
120,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,30.840

In [16]:
# Use `.iloc[]` to select the first 5 rows and last 3 columns.
df.iloc[:5, -3:]

   Quantity  Discount    Profit
0         2      0.00   41.9136
1         3      0.00  219.5820
2         2      0.00    6.8714
3         5      0.45 -383.0310
4         2      0.20    2.5164

In [17]:
# Filter rows where `Category == 'Technology'` and `Profit > 0`.
df[(df['Category']=='Technology') & (df['Profit']>0)]

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
7,8,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6,0.2,90.7152
11,12,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.424,4,0.2,68.3568
19,20,CA-2011-143336,2011,8/27/2011,2011-01-09 00:00:00,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,...,94109,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.480,3,0.2,16.0110
26,27,CA-2013-121755,2013,1/16/2013,1/20/2013,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,...,90049,West,TEC-AC-10003027,Technology,Accessories,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive,90.570,3,0.0,11.7741
35,36,CA-2013-117590,2013,2013-09-12 00:00:00,2013-11-12 00:00:00,First Class,GH-14485,Gene Hale,Corporate,United States,...,75080,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544,7,0.2,123.4737
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9983,9984,US-2013-157728,2013,9/23/2013,9/29/2013,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,...,49505,Central,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.980,2,0.0,27.4344
9986,9987,CA-2013-125794,2013,9/30/2013,2013-04-10 00:00:00,Standard Class,ML-17410,Maris LaWare,Consumer,United States,...,90008,West,TEC-AC-10003399,Technology,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.240,1,0.0,15.2208
9987,9988,CA-2014-163629,2014,11/18/2014,11/22/2014,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,...,30605,South,TEC-AC-10001539,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,79.990,1,0.0,28.7964
9988,9989,CA-2014-163629,2014,11/18/2014,11/22/2014,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.100,5,0.0,55.6470
9991,9992,CA-2014-121258,2014,2/27/2014,2014-04-03 00:00:00,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932

In [18]:
# Select all orders placed in the 'West' region by 'Consumer' segment.
df[(df['Region']=='West') & (df['Segment']=='Consumer')]

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
5,6,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
6,7,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656
7,8,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6,0.2,90.7152
8,9,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825
9,10,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.900,5,0.0,34.4700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9986,9987,CA-2013-125794,2013,9/30/2013,2013-04-10 00:00:00,Standard Class,ML-17410,Maris LaWare,Consumer,United States,...,90008,West,TEC-AC-10003399,Technology,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.240,1,0.0,15.2208
9990,9991,CA-2014-121258,2014,2/27/2014,2014-04-03 00:00:00,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2014-121258,2014,2/27/2014,2014-04-03 00:00:00,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2014-121258,2014,2/27/2014,2014-04-03 00:00:00,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2014-119914,2014,2014-05-05 00:00:00,2014-10-05 00:00:00,Second Class,CC-12220,Chris Cortes,Consumer,United States,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [19]:
# Use boolean indexing to find all rows with a `Discount` of 0.
df[df['Discount']==0]

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
2,3,CA-2013-138688,2013,6/13/2013,6/17/2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714
5,6,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.86,7,0.0,14.1694
6,7,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.28,4,0.0,1.9656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,9988,CA-2014-163629,2014,11/18/2014,11/22/2014,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,...,30605,South,TEC-AC-10001539,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,79.99,1,0.0,28.7964
9988,9989,CA-2014-163629,2014,11/18/2014,11/22/2014,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.10,5,0.0,55.6470
9990,9991,CA-2014-121258,2014,2/27/2014,2014-04-03 00:00:00,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.96,2,0.0,15.6332
9992,9993,CA-2014-121258,2014,2/27/2014,2014-04-03 00:00:00,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.60,4,0.0,13.3200
9993,9994,CA-2014-119914,2014,2014-05-05 00:00:00,2014-10-05 00:00:00,Second Class,CC-12220,Chris Cortes,Consumer,United States,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.9480

In [20]:
# Select rows where `Ship Mode` is either 'First Class' or 'Same Day'.
df[df['Ship Mode'].isin(['First Class','Same Day'])]

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
35,36,CA-2013-117590,2013,2013-09-12 00:00:00,2013-11-12 00:00:00,First Class,GH-14485,Gene Hale,Corporate,United States,...,75080,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.5440,7,0.20,123.4737
36,37,CA-2013-117590,2013,2013-09-12 00:00:00,2013-11-12 00:00:00,First Class,GH-14485,Gene Hale,Corporate,United States,...,75080,Central,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",190.9200,5,0.60,-147.9630
44,45,CA-2013-118255,2013,2013-12-03 00:00:00,3/14/2013,First Class,ON-18715,Odella Nelson,Corporate,United States,...,55122,Central,TEC-AC-10000171,Technology,Accessories,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,45.9800,2,0.00,19.7714
45,46,CA-2013-118255,2013,2013-12-03 00:00:00,3/14/2013,First Class,ON-18715,Odella Nelson,Corporate,United States,...,55122,Central,OFF-BI-10003291,Office Supplies,Binders,Wilson Jones Leather-Like Binders with DublLoc...,17.4600,2,0.00,8.2062
55,56,CA-2013-111682,2013,6/18/2013,6/19/2013,First Class,TB-21055,Ted Butterfield,Consumer,United States,...,12180,East,OFF-ST-10000604,Office Supplies,Storage,Home/Office Personal File Carts,208.5600,6,0.00,52.1400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9933,9934,CA-2011-166555,2011,2011-11-07 00:00:00,7/14/2011,First Class,JK-15205,Jamie Kunitz,Consumer,United States,...,14304,East,TEC-PH-10004912,Technology,Phones,Cisco SPA112 2 Port Phone Adapter,164.8500,3,0.00,47.8065
9961,9962,CA-2012-168088,2012,3/19/2012,3/22/2012,First Class,CM-12655,Corinna Mitchell,Home Office,United States,...,77041,Central,OFF-PA-10000675,Office Supplies,Paper,Xerox 1919,65.5840,2,0.20,23.7742
9962,9963,CA-2012-168088,2012,3/19/2012,3/22/2012,First Class,CM-12655,Corinna Mitchell,Home Office,United States,...,77041,Central,FUR-BO-10004218,Furniture,Bookcases,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,4,0.32,-67.6704
9963,9964,CA-2012-143700,2012,7/26/2012,7/26/2012,Same Day,AS-10240,Alan Shonely,Consumer,United States,...,19140,East,OFF-PA-10003072,Office Supplies,Paper,"Eureka Recycled Copy Paper 8 1/2"" x 11"", Ream",10.3680,2,0.20,3.6288
9981,9982,CA-2014-163566,2014,2014-04-08 00:00:00,2014-07-08 00:00:00,First Class,TB-21055,Ted Butterfield,Consumer,United States,...,45014,East,OFF-LA-10004484,Office Supplies,Labels,Avery 476,16.5200,5,0.20,5.3690

In [21]:
# Find all orders where `Quantity` is between 5 and 10 (inclusive).
df[df['Quantity'].between(5,10)]

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
3,4,US-2012-108966,2012,2012-11-10 00:00:00,10/18/2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
5,6,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
7,8,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
9,10,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700
10,11,CA-2011-115812,2011,2011-09-06 00:00:00,6/14/2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,9978,US-2013-103674,2013,2013-07-12 00:00:00,2013-11-12 00:00:00,Standard Class,AP-10720,Anne Pryor,Home Office,United States,...,90032,West,OFF-FA-10003467,Office Supplies,Fasteners,"Alliance Big Bands Rubber Bands, 12/Pack",13.8600,7,0.00,0.0000
9981,9982,CA-2014-163566,2014,2014-04-08 00:00:00,2014-07-08 00:00:00,First Class,TB-21055,Ted Butterfield,Consumer,United States,...,45014,East,OFF-LA-10004484,Office Supplies,Labels,Avery 476,16.5200,5,0.20,5.3690
9982,9983,US-2013-157728,2013,9/23/2013,9/29/2013,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,...,49505,Central,OFF-PA-10002195,Office Supplies,Paper,"RSVP Cards & Envelopes, Blank White, 8-1/2"" X ...",35.5600,7,0.00,16.7132
9984,9985,CA-2012-100251,2012,5/17/2012,5/23/2012,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,...,11561,East,OFF-LA-10003766,Office Supplies,Labels,Self-Adhesive Removable Labels,31.5000,10,0.00,15.1200
9988,9989,CA-2014-163629,2014,11/18/2014,11/22/2014,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.1000,5,0.00,55.6470

In [22]:
# Select the row with the highest `Sales` value using `.idxmax()`.
df.loc[df['Sales'].idxmax()]

Row ID                                                        2698
Order ID                                            CA-2011-145317
Year                                                          2011
Order Date                                               3/18/2011
Ship Date                                                3/23/2011
Ship Mode                                           Standard Class
Customer ID                                               SM-20320
Customer Name                                          Sean Miller
Segment                                                Home Office
Country                                              United States
City                                                  Jacksonville
State                                                      Florida
Postal Code                                                  32216
Region                                                       South
Product ID                                         TEC-MA-10002412
Category                                                Technology
Sub-Category                                              Machines
Product Name     Cisco TelePresence System EX90 Videoconferenci...
Sales                                                     22638.48
Quantity                                                         6
Discount                                                       0.5
Profit                                                  -1811.0784
Name: 2697, dtype: object

In [23]:
# Check for duplicate rows in the DataFrame and print the count.
df.duplicated().sum()

np.int64(0)

In [24]:
# Drop all duplicate rows if any exist.
df.drop_duplicates(inplace=True)

In [26]:
# Rename columns 'Sub-Category' to 'SubCategory' and 'Ship Mode' to 'ShipMode'.
df.rename(columns={'Sub-Category':'SubCategory','Ship Mode':'ShipMode'}, inplace=True)

In [27]:
df.columns

Index(['Row ID', 'Order ID', 'Year', 'Order Date', 'Ship Date', 'ShipMode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'SubCategory',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [30]:
# Convert the 'Order Date' column to datetime format using `pd.to_datetime()`
df['Order Date']=pd.to_datetime(df['Order Date'])

In [31]:
# Strip leading/trailing whitespace from all string columns.
df = df.apply(lambda x: x.str.strip() if x.dtype=='object' else x)

In [32]:
# Replace all negative `Profit` values with 0.
df['Profit']=df['Profit'].apply(lambda x:0 if x<0 else x)

In [33]:
# Fill any missing values in the 'Postal Code' column with 0.
df['Postal Code']=df['Postal Code'].fillna(0)

In [34]:
# Cast the 'Year' column to string type.
df['Year']=df['Year'].astype(str)

In [35]:
# Reset the DataFrame index and drop the old one.
df.reset_index(drop=True,inplace=True)

In [36]:
# Create a clean copy of the DataFrame without the 'Row ID' and 'Country' columns.
df_clean=df.drop(columns=['Row ID','Country'],errors='ignore')

# AGGREGATION

In [37]:
# Calculate the total `Sales`, `Profit`, and `Quantity` for the entire dataset.
df[['Sales','Profit','Quantity']].sum()

Sales       2.297201e+06
Profit      4.425283e+05
Quantity    3.787300e+04
dtype: float64

In [38]:
# Find the average `Discount` applied per `Category`.
df.groupby('Category')['Discount'].mean()

Category
Furniture          0.173923
Office Supplies    0.157285
Technology         0.132323
Name: Discount, dtype: float64

In [39]:
# Count the number of orders (rows) per `Region`.
df['Region'].value_counts()

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

In [40]:
# Find the maximum and minimum `Sales` in each `Segment`.
df.groupby('Segment')['Sales'].agg(['max','min'])

                  max    min
Segment
Consumer     13999.96  0.444
Corporate    17499.95  0.556
Home Office  22638.48  0.990

In [41]:
# Calculate total `Profit` per `Sub-Category` and sort descending.
df.groupby('SubCategory')['Profit'].sum().sort_values(ascending=False)

SubCategory
Binders        68732.2597
Copiers        55617.8249
Phones         52046.3541
Accessories    42867.2622
Chairs         36471.0076
Paper          34053.5693
Machines       33503.4251
Storage        27705.1302
Appliances     26767.6466
Furnishings    19550.0570
Tables         14686.6672
Bookcases       8679.6500
Envelopes       6964.1767
Art             6527.7870
Labels          5546.2540
Supplies        1826.5224
Fasteners        982.7134
Name: Profit, dtype: float64

In [42]:
# Use `.agg()` to compute mean, max, and min of `Sales` grouped by `Ship Mode`
df.groupby('ShipMode')['Sales'].agg(['mean','max','min'])

                      mean       max    min
ShipMode
First Class     228.497024  13999.96  0.984
Same Day        236.396179   7999.98  0.556
Second Class    236.089239   8749.95  1.188
Standard Class  227.583067  22638.48  0.444

In [43]:
# Find the total number of unique customers in the dataset.
df['Customer ID'].nunique()

793

In [44]:
# Calculate total `Sales` per `Year` and compute year-over-year growth %.
year_sales=df.groupby('Year')['Sales'].sum(); year_sales.pct_change()*100

Year
2011          NaN
2012    -2.832227
2013    29.316002
2014    20.620968
Name: Sales, dtype: float64

In [45]:
# Find the top 5 states by total `Sales`.
df.groupby('State')['Sales'].sum().nlargest(5)

State
California      457687.6315
New York        310876.2710
Texas           170188.0458
Washington      138641.2700
Pennsylvania    116511.9140
Name: Sales, dtype: float64

In [46]:
# Compute the profit margin (Profit/Sales * 100) grouped by `Category`.
(df.groupby('Category')['Profit'].sum()/df.groupby('Category')['Sales'].sum())*100

Category
Furniture          10.699111
Office Supplies    24.908810
Technology         22.009685
dtype: float64

# GROUPBY

In [47]:
# Group by `Category` and `Sub-Category`, then sum `Sales` and `Profit`.
df.groupby(['Category','SubCategory'])[['Sales','Profit']].sum()

                                   Sales      Profit
Category        SubCategory
Furniture       Bookcases    114879.9963   8679.6500
                Chairs       328449.1030  36471.0076
                Furnishings   91705.1640  19550.0570
                Tables       206965.5320  14686.6672
Office Supplies Appliances   107532.1610  26767.6466
                Art           27118.7920   6527.7870
                Binders      203412.7330  68732.2597
                Envelopes     16476.4020   6964.1767
                Fasteners      3024.2800    982.7134
                Labels        12486.3120   5546.2540
                Paper         78479.2060  34053.5693
                Storage      223843.6080  27705.1302
                Supplies      46673.5380   1826.5224
Technology      Accessories  167380.3180  42867.2622
                Copiers      149528.0300  55617.8249
                Machines     189238.6310  33503.4251
                Phones       330007.0540  52046.3541

In [48]:
# Group by `Year` and `Segment`, then find average `Sales`.
df.groupby(['Year','Segment'])['Sales'].mean()

Year  Segment
2011  Consumer       248.688610
      Corporate      210.204376
      Home Office    287.550679
2012  Consumer       236.920830
      Corporate      202.448596
      Home Office    220.643017
2013  Consumer       223.957324
      Corporate      261.621939
      Home Office    225.826903
2014  Consumer       198.728667
      Corporate      246.447284
      Home Office    240.154715
Name: Sales, dtype: float64

In [49]:
# Use `groupby` and `transform` to add a column 'Avg_Category_Sales' = mean sales per category.
df['Avg_Category_Sales']=df.groupby('Category')['Sales'].transform('mean')

In [50]:
# Group by `Region` and count distinct `Customer ID` values.
df.groupby('Region')['Customer ID'].nunique()

Region
Central    629
East       674
South      512
West       686
Name: Customer ID, dtype: int64

In [51]:
# Group by `Ship Mode` and calculate the total `Quantity` shipped.
df.groupby('ShipMode')['Quantity'].sum()

ShipMode
First Class        5693
Same Day           1960
Second Class       7423
Standard Class    22797
Name: Quantity, dtype: int64

In [52]:
# Group by `Year` and `Category` and find the total profit. Unstack the result.
df.groupby(['Year','Category'])['Profit'].sum().unstack()

Category   Furniture  Office Supplies  Technology
Year
2011      16024.4892       35796.2978  29615.9588
2012      18774.0038       35950.0048  39423.9860
2013      22278.4976       45799.7211  51486.4266
2014      22310.3912       61560.0356  63508.4949

In [53]:
# Find the customer who spent the most in total `Sales`.
df.groupby('Customer Name')['Sales'].sum().idxmax()

'Sean Miller'

In [54]:
# Group by `Segment` and compute the sum of discounts applied.
df.groupby('Segment')['Discount'].sum()

Segment
Consumer       820.91
Corporate      477.85
Home Office    262.33
Name: Discount, dtype: float64

In [55]:
# Use `groupby` + `filter` to keep only categories where average profit > 100.
df.groupby('Category').filter(lambda x:x['Profit'].mean()>100)

Empty DataFrame
Columns: [Row ID, Order ID, Year, Order Date, Ship Date, ShipMode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, SubCategory, Product Name, Sales, Quantity, Discount, Profit, Avg_Category_Sales]
Index: []

[0 rows x 23 columns]

In [56]:
# Group by `State` and find the number of orders and average sales per state.
df.groupby('State').agg({'Order ID':'count','Sales':'mean'})

                      Order ID        Sales
State
Alabama                     61   319.846557
Arizona                    224   157.508933
Arkansas                    60   194.635500
California                2001   228.729451
Colorado                   182   176.418231
Connecticut                 82   163.223866
Delaware                    96   285.948635
District of Columbia        10   286.502000
Florida                    383   233.612815
Georgia                    184   266.825217
Idaho                       21   208.689810
Illinois                   492   162.939230
Indiana                    149   359.431946
Iowa                        30   152.658667
Kansas                      24   121.429583
Kentucky                   139   263.250000
Louisiana                   42   219.453095
Maine                        8   158.816250
Maryland                   105   225.766886
Massachusetts              135   212.106919
Michigan                   255   299.096525
Minnesota                   89   335.541011
Mississippi                 53   203.232830
Missouri                    66   336.441667
Montana                     15   372.623467
Nebraska                    38   196.445526
Nevada                      39   428.951333
New Hampshire               27   270.093481
New Jersey                 130   275.110092
New Mexico                  37   129.284378
New York                  1128   275.599531
North Carolina             249   223.305880
North Dakota                 7   131.415714
Ohio                       469   166.861697
Oklahoma                    66   298.233182
Oregon                     124   140.573790
Pennsylvania               587   198.487077
Rhode Island                56   404.070643
South Carolina              42   201.945476
South Dakota                12   109.630000
Tennessee                  183   167.551219
Texas                      985   172.779742
Utah                        53   211.699170
Vermont                     11   811.760909
Virginia                   224   315.342500
Washington                 506   273.994605
West Virginia                4   302.456000
Wisconsin                  110   291.951000
Wyoming                      1  1603.136000

# STRINGS OPS

In [57]:
# Extract the first 2 characters of each `Order ID` as a new column 'Order_Prefix'.
df['Order_Prefix']=df['Order ID'].str[:2]

In [58]:
# Convert all values in the `Customer Name` column to uppercase.
df['Customer Name']=df['Customer Name'].str.upper()

In [59]:
# Count how many product names contain the word 'Chair' (case-insensitive).
df['Product Name'].str.contains('chair',case=False).sum()

np.int64(701)

In [64]:
# Split `Customer Name` into 'First_Name' and 'Last_Name' columns.
df[['First_Name', 'Last_Name']] = df['Customer Name'].str.split(n=1, expand=True)

In [65]:
# Find all orders where `Product Name` starts with 'Staple'.
df[df['Product Name'].str.startswith('Staple')]

,Row ID,Order ID,Year,Order Date,Ship Date,ShipMode,Customer ID,Customer Name,Segment,Country,...,SubCategory,Product Name,Sales,Quantity,Discount,Profit,Avg_Category_Sales,Order_Prefix,First_Name,Last_Name
34,35,CA-2014-107727,2014,2014-10-20,10/24/2014,Second Class,MA-17560,MATT ABELMAN,Home Office,United States,...,Paper,Staples,29.472,3,0.2,9.9468,119.324101,CA,MATT,ABELMAN
132,133,US-2014-164147,2014,2014-03-02,NaN,First Class,DW-13585,DOROTHY WARDLE,Corporate,United States,...,Fasteners,Staples,21.456,9,0.2,6.9732,119.324101,US,DOROTHY,WARDLE
162,163,CA-2013-154508,2013,2013-11-17,11/21/2013,Standard Class,RD-19900,RUBEN DARTT,Consumer,United States,...,Envelopes,Staples,28.400,5,0.0,13.3480,119.324101,CA,RUBEN,DARTT
239,240,CA-2013-157749,2013,2013-05-06,NaN,Second Class,KL-16645,KEN LONSDALE,Consumer,United States,...,Furnishings,Staples,11.688,3,0.6,0.0000,349.834887,CA,KEN,LONSDALE
283,284,CA-2012-130883,2012,2012-09-26,NaN,Standard Class,TB-21520,TRACY BLUMSTEIN,Consumer,United States,...,Paper,Staples,141.760,5,0.2,47.8440,119.324101,CA,TRACY,BLUMSTEIN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9861,9862,CA-2014-113278,2014,2014-01-15,1/21/2014,Standard Class,HR-14770,HALLIE REDMOND,Home Office,United States,...,Storage,Staples,18.760,2,0.0,5.2528,119.324101,CA,HALLIE,REDMOND
9872,9873,CA-2014-146269,2014,2014-07-10,NaN,Same Day,MH-17455,MARK HAMILTON,Consumer,United States,...,Art,Staples,19.152,2,0.2,1.1970,119.324101,CA,MARK,HAMILTON
9880,9881,CA-2012-104297,2012,2012-05-29,5/31/2012,First Class,CC-12100,CHAD CUNNINGHAM,Home Office,United States,...,Paper,Staples,85.056,3,0.2,28.7064,119.324101,CA,CHAD,CUNNINGHAM
9883,9884,CA-2011-112291,2011,2011-03-04,NaN,Standard Class,KE-16420,KATRINA EDELMAN,Corporate,United States,...,Envelopes,Staples,11.160,2,0.0,5.5800,119.324101,CA,KATRINA,EDELMAN
9965,9966,CA-2013-146374,2013,2013-06-12,NaN,Second Class,HE-14800,HAROLD ENGLE,Corporate,United States,...,Paper,Staples,4.980,1,0.0,2.3406,119.324101,CA,HAROLD,ENGLE

In [66]:
# Replace 'Home Office' with 'Home_Office' in the `Segment` column.
df['Segment']=df['Segment'].replace('Home Office','Home_Office')

In [67]:
# Use `.str.contains()` to filter rows where `City` contains 'New'.
df[df['City'].str.contains('New',na=False)]

,Row ID,Order ID,Year,Order Date,Ship Date,ShipMode,Customer ID,Customer Name,Segment,Country,...,SubCategory,Product Name,Sales,Quantity,Discount,Profit,Avg_Category_Sales,Order_Prefix,First_Name,Last_Name
49,50,CA-2012-115742,2012,2012-04-18,4/22/2012,Standard Class,DP-13000,DARREN POWERS,Consumer,United States,...,Binders,"C-Line Peel & Stick Add-On Filing Pockets, 8-3...",38.22,6,0.0,17.9634,119.324101,CA,DARREN,POWERS
50,51,CA-2012-115742,2012,2012-04-18,4/22/2012,Standard Class,DP-13000,DARREN POWERS,Consumer,United States,...,Labels,Avery 485,75.18,6,0.0,35.3346,119.324101,CA,DARREN,POWERS
51,52,CA-2012-115742,2012,2012-04-18,4/22/2012,Standard Class,DP-13000,DARREN POWERS,Consumer,United States,...,Furnishings,Longer-Life Soft White Bulbs,6.16,2,0.0,2.9568,349.834887,CA,DARREN,POWERS
52,53,CA-2012-115742,2012,2012-04-18,4/22/2012,Standard Class,DP-13000,DARREN POWERS,Consumer,United States,...,Chairs,"Global Leather Task Chair, Black",89.99,1,0.0,17.0981,349.834887,CA,DARREN,POWERS
53,54,CA-2013-105816,2013,2013-12-12,12/18/2013,Standard Class,JM-15265,JANET MOLINARI,Corporate,United States,...,Fasteners,Advantus Push Pins,15.26,7,0.0,6.2566,119.324101,CA,JANET,MOLINARI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9957,9958,US-2011-143287,2011,2011-11-11,11/17/2011,Standard Class,KN-16705,KRISTINA NUNN,Home_Office,United States,...,Paper,Xerox 1882,223.92,4,0.0,109.7208,119.324101,US,KRISTINA,NUNN
9958,9959,US-2011-143287,2011,2011-11-11,11/17/2011,Standard Class,KN-16705,KRISTINA NUNN,Home_Office,United States,...,Supplies,Acme Value Line Scissors,7.30,2,0.0,2.1900,119.324101,US,KRISTINA,NUNN
9964,9965,CA-2013-146374,2013,2013-06-12,NaN,Second Class,HE-14800,HAROLD ENGLE,Corporate,United States,...,Furnishings,Electrix 20W Halogen Replacement Bulb for Zoom...,13.40,1,0.0,6.4320,349.834887,CA,HAROLD,ENGLE
9965,9966,CA-2013-146374,2013,2013-06-12,NaN,Second Class,HE-14800,HAROLD ENGLE,Corporate,United States,...,Paper,Staples,4.98,1,0.0,2.3406,119.324101,CA,HAROLD,ENGLE
9966,9967,CA-2013-146374,2013,2013-06-12,NaN,Second Class,HE-14800,HAROLD ENGLE,Corporate,United States,...,Envelopes,"#10 White Business Envelopes,4 1/8 x 9 1/2",109.69,7,0.0,51.5543,119.324101,CA,HAROLD,ENGLE

In [68]:
# Count the number of characters in each `Product Name` and add as a column.
df['Product_Name_Length']=df['Product Name'].str.len()

# DATETIME

In [70]:
# Extract the month number from `Order Date` into a new column 'Order_Month'.
df['Order_Month']=df['Order Date'].dt.month

In [71]:
# Extract the day of the week from `Ship Date` into a new column 'Ship_Weekday'.
df['Ship_Weekday']=pd.to_datetime(df['Ship Date']).dt.day_name()

In [72]:
# Calculate the number of days between `Order Date` and `Ship Date` as 'Shipping_Days'.
df['Shipping_Days']=(pd.to_datetime(df['Ship Date'])-df['Order Date']).dt.days

In [73]:
# Find the month with the highest total `Sales`.
df.groupby(df['Order Date'].dt.month)['Sales'].sum().idxmax()

np.int32(11)

In [74]:
# Filter all orders placed in Q4 (October–December).
df[df['Order Date'].dt.month.isin([10,11,12])]

,Row ID,Order ID,Year,Order Date,Ship Date,ShipMode,Customer ID,Customer Name,Segment,Country,...,Discount,Profit,Avg_Category_Sales,Order_Prefix,First_Name,Last_Name,Product_Name_Length,Order_Month,Ship_Weekday,Shipping_Days
3,4,US-2012-108966,2012,2012-11-10,10/18/2012,Standard Class,SO-20335,SEAN O'DONNELL,Consumer,United States,...,0.45,0.0000,349.834887,US,SEAN,O'DONNELL,45,11,Thursday,-23.0
4,5,US-2012-108966,2012,2012-11-10,10/18/2012,Standard Class,SO-20335,SEAN O'DONNELL,Consumer,United States,...,0.20,2.5164,119.324101,US,SEAN,O'DONNELL,30,11,Thursday,-23.0
14,15,US-2012-118983,2012,2012-11-22,11/26/2012,Standard Class,HP-14815,HAROLD PAWLAN,Home_Office,United States,...,0.80,0.0000,119.324101,US,HAROLD,PAWLAN,76,11,Monday,4.0
15,16,US-2012-118983,2012,2012-11-22,11/26/2012,Standard Class,HP-14815,HAROLD PAWLAN,Home_Office,United States,...,0.80,0.0000,119.324101,US,HAROLD,PAWLAN,48,11,Monday,4.0
16,17,CA-2011-105893,2011,2011-11-11,11/18/2011,Standard Class,PK-19075,PETE KRIZ,Consumer,United States,...,0.00,13.3176,119.324101,CA,PETE,KRIZ,62,11,Friday,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9968,9969,CA-2014-153871,2014,2014-12-12,12/18/2014,Standard Class,RB-19435,RICHARD BIERNER,Consumer,United States,...,0.00,331.1910,119.324101,CA,RICHARD,BIERNER,41,12,Thursday,6.0
9969,9970,CA-2014-153871,2014,2014-12-12,12/18/2014,Standard Class,RB-19435,RICHARD BIERNER,Consumer,United States,...,0.00,6.5975,119.324101,CA,RICHARD,BIERNER,79,12,Thursday,6.0
9972,9973,CA-2013-130225,2013,2013-12-09,9/18/2013,Standard Class,RC-19960,RYAN CROWE,Consumer,United States,...,0.20,33.6042,119.324101,CA,RYAN,CROWE,27,12,Wednesday,-82.0
9987,9988,CA-2014-163629,2014,2014-11-18,11/22/2014,Standard Class,RA-19885,RUBEN AUSMAN,Corporate,United States,...,0.00,28.7964,452.709276,CA,RUBEN,AUSMAN,69,11,Saturday,4.0
9988,9989,CA-2014-163629,2014,2014-11-18,11/22/2014,Standard Class,RA-19885,RUBEN AUSMAN,Corporate,United States,...,0.00,55.6470,452.709276,CA,RUBEN,AUSMAN,31,11,Saturday,4.0

In [75]:
# Count the number of orders placed on weekends.
df[df['Order Date'].dt.dayofweek>=5].shape[0]

1818

In [77]:
# Resample `Sales` by month (set Order Date as index) to get monthly totals.
df.set_index('Order Date')['Sales'].resample('ME').sum()

Order Date
2011-01-31    28484.8060
2011-02-28    13129.9300
2011-03-31    54899.9920
2011-04-30    24401.1320
2011-05-31    30042.7420
2011-06-30    24568.9546
2011-07-31    39811.3800
2011-08-31    38107.4655
2011-09-30    66084.2398
2011-10-31    34547.6610
2011-11-30    62819.1085
2011-12-31    67350.0867
2012-01-31    29087.9304
2012-02-29    20987.8080
2012-03-31    40876.6112
2012-04-30    38056.9685
2012-05-31    30933.7145
2012-06-30    28862.1982
2012-07-31    28730.3760
2012-08-31    50094.5280
2012-09-30    66729.3290
2012-10-31    32025.0750
2012-11-30    50732.3090
2012-12-31    53415.6612
2013-01-31    21998.1470
2013-02-28    41411.8460
2013-03-31    61470.8110
2013-04-30    48654.4390
2013-05-31    66946.5680
2013-06-30    44643.4538
2013-07-31    40454.6170
2013-08-31    45065.8533
2013-09-30    55505.9529
2013-10-31    34980.5330
2013-11-30    72985.8510
2013-12-31    74355.7580
2014-01-31    58016.2488
2014-02-28    44845.3254
2014-03-31    80235.3360
2014-04-30    43204.2416
2014-05-31    47320.4404
2014-06-30    48030.5177
2014-07-31    40366.3518
2014-08-31    74492.3475
2014-09-30    77790.2180
2014-10-31    76203.1362
2014-11-30    84924.4660
2014-12-31    58518.3938
Freq: ME, Name: Sales, dtype: float64

In [78]:
# Find the fastest-shipped order (minimum shipping days).
df.loc[df['Shipping_Days'].idxmin()]

Row ID                                                             717
Order ID                                                CA-2011-130092
Year                                                              2011
Order Date                                         2011-12-01 00:00:00
Ship Date                                                    1/15/2011
ShipMode                                                   First Class
Customer ID                                                   SV-20365
Customer Name                                              SETH VERNON
Segment                                                       Consumer
Country                                                  United States
City                                                             Dover
State                                                         Delaware
Postal Code                                                      19901
Region                                                            East
Product ID                                             FUR-FU-10000010
Category                                                     Furniture
SubCategory                                                Furnishings
Product Name           DAX Value U-Channel Document Frames, Easel Back
Sales                                                             9.94
Quantity                                                             2
Discount                                                           0.0
Profit                                                          3.0814
Avg_Category_Sales                                          349.834887
Order_Prefix                                                        CA
First_Name                                                        SETH
Last_Name                                                       VERNON
Product_Name_Length                                                 47
Order_Month                                                         12
Ship_Weekday                                                  Saturday
Shipping_Days                                                   -320.0
Name: 716, dtype: object

# Merge/Reshape

In [79]:
# Create a pivot table of total `Sales` with `Year` as rows and `Category` as columns.
pd.pivot_table(df,values='Sales',index='Year',columns='Category',aggfunc='sum')

Category    Furniture  Office Supplies  Technology
Year
2011      157192.8531       151776.412  175278.233
2012      170518.2370       137233.463  162780.809
2013      198901.4360       183510.590  226061.804
2014      215387.2692       246526.567  272033.187

In [80]:
# Create a pivot table of average `Profit` by `Region` and `Segment`.
pd.pivot_table(df,values='Profit',index='Region',columns='Segment',aggfunc='mean')

Segment   Consumer  Corporate  Home_Office
Region
Central  35.639030  49.003426    45.313784
East     47.067824  45.002070    64.748882
South    46.995019  48.290297    37.663180
West     40.278682  41.346009    42.208904

In [81]:
# Use `pd.melt()` to unpivot the pivot table from Q67 into a long format.
pivot=pd.pivot_table(df,values='Sales',index='Year',columns='Category',aggfunc='sum'); pd.melt(pivot.reset_index(),id_vars='Year')

    Year         Category        value
0   2011        Furniture  157192.8531
1   2012        Furniture  170518.2370
2   2013        Furniture  198901.4360
3   2014        Furniture  215387.2692
4   2011  Office Supplies  151776.4120
5   2012  Office Supplies  137233.4630
6   2013  Office Supplies  183510.5900
7   2014  Office Supplies  246526.5670
8   2011       Technology  175278.2330
9   2012       Technology  162780.8090
10  2013       Technology  226061.8040
11  2014       Technology  272033.1870

In [82]:
# Create a crosstab of `Region` vs `Segment` showing count of orders.
pd.crosstab(df['Region'],df['Segment'])

Segment  Consumer  Corporate  Home_Office
Region
Central      1212        673          438
East         1469        877          502
South         838        510          272
West         1672        960          571

In [83]:
# Split the DataFrame into two: df_tech (Technology) and df_other (rest), then concatenate them back.
df_tech=df[df['Category']=='Technology']; df_other=df[df['Category']!='Technology']; pd.concat([df_tech,df_other])

,Row ID,Order ID,Year,Order Date,Ship Date,ShipMode,Customer ID,Customer Name,Segment,Country,...,Discount,Profit,Avg_Category_Sales,Order_Prefix,First_Name,Last_Name,Product_Name_Length,Order_Month,Ship_Weekday,Shipping_Days
7,8,CA-2011-115812,2011,2011-09-06,6/14/2011,Standard Class,BH-11710,BROSINA HOFFMAN,Consumer,United States,...,0.2,90.7152,452.709276,CA,BROSINA,HOFFMAN,30,9,Tuesday,-84.0
11,12,CA-2011-115812,2011,2011-09-06,6/14/2011,Standard Class,BH-11710,BROSINA HOFFMAN,Consumer,United States,...,0.2,68.3568,452.709276,CA,BROSINA,HOFFMAN,45,9,Tuesday,-84.0
19,20,CA-2011-143336,2011,2011-08-27,NaN,Second Class,ZD-21925,ZUSCHUSS DONATELLI,Consumer,United States,...,0.2,16.0110,452.709276,CA,ZUSCHUSS,DONATELLI,23,8,NaN,NaN
26,27,CA-2013-121755,2013,2013-01-16,1/20/2013,Second Class,EH-13945,ERIC HOFFMANN,Consumer,United States,...,0.0,11.7741,452.709276,CA,ERIC,HOFFMANN,48,1,Sunday,4.0
35,36,CA-2013-117590,2013,2013-09-12,NaN,First Class,GH-14485,GENE HALE,Corporate,United States,...,0.2,123.4737,452.709276,CA,GENE,HALE,11,9,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9985,9986,CA-2012-100251,2012,2012-05-17,5/23/2012,Standard Class,DV-13465,DIANNA VITTORINI,Consumer,United States,...,0.0,16.1240,119.324101,CA,DIANNA,VITTORINI,81,5,Wednesday,6.0
9989,9990,CA-2011-110422,2011,2011-01-22,1/24/2011,Second Class,TB-21400,TOM BOECKENHAUER,Consumer,United States,...,0.2,4.1028,349.834887,CA,TOM,BOECKENHAUER,22,1,Monday,2.0
9990,9991,CA-2014-121258,2014,2014-02-27,NaN,Standard Class,DB-13060,DAVE BROOKS,Consumer,United States,...,0.0,15.6332,349.834887,CA,DAVE,BROOKS,50,2,NaN,NaN
9992,9993,CA-2014-121258,2014,2014-02-27,NaN,Standard Class,DB-13060,DAVE BROOKS,Consumer,United States,...,0.0,13.3200,119.324101,CA,DAVE,BROOKS,49,2,NaN,NaN
9993,9994,CA-2014-119914,2014,2014-05-05,NaN,Second Class,CC-12220,CHRIS CORTES,Consumer,United States,...,0.0,72.9480,119.324101,CA,CHRIS,CORTES,73,5,NaN,NaN

In [84]:
# Create a summary DataFrame of total Sales per Category and merge it back onto the main df as 'Category_Total_Sales'.
cat_sales=df.groupby('Category')['Sales'].sum().reset_index(name='Category_Total_Sales'); df=df.merge(cat_sales,on='Category')

In [85]:
# Use `pd.cut()` to bin `Sales` into 'Low', 'Medium', 'High', 'Very High' and add as 'Sales_Bin'.
df['Sales_Bin']=pd.cut(df['Sales'],bins=4,labels=['Low','Medium','High','Very High'])

In [86]:
# Use `pd.qcut()` to divide `Profit` into 4 equal-frequency quartiles.
df['Profit_Quartile']=pd.qcut(df['Profit'],4)

In [87]:
# Stack and unstack the multi-level index from the Year × Category groupby result.
g=df.groupby(['Year','Category'])['Sales'].sum(); g.unstack().stack()

Year  Category
2011  Furniture          157192.8531
      Office Supplies    151776.4120
      Technology         175278.2330
2012  Furniture          170518.2370
      Office Supplies    137233.4630
      Technology         162780.8090
2013  Furniture          198901.4360
      Office Supplies    183510.5900
      Technology         226061.8040
2014  Furniture          215387.2692
      Office Supplies    246526.5670
      Technology         272033.1870
dtype: float64

# Advanced

In [88]:
# Use `.apply()` to create a 'Profit_Category' column: 'Loss' if Profit < 0, 'Low' if < 50, 'High' otherwise.
df['Profit_Category']=df['Profit'].apply(lambda x:'Loss' if x<0 else ('Low' if x<50 else 'High'))

In [89]:
# Use `.map()` to encode the `Segment` column as numbers (Consumer=0, Corporate=1, Home Office=2).
df['Segment_Code']=df['Segment'].map({'Consumer':0,'Corporate':1,'Home_Office':2})

In [90]:
# Use `np.where()` to flag orders with Discount > 0.3 as 'Heavy Discount' else 'Normal'.
df['Discount_Flag']=np.where(df['Discount']>0.3,'Heavy Discount','Normal')

In [92]:
# Compute a rolling 3-month average of `Sales` after resampling by month.
df.set_index('Order Date')['Sales'].resample('ME').mean().rolling(3).mean()

Order Date
2011-01-31           NaN
2011-02-28           NaN
2011-03-31    233.456441
2011-04-30    229.348229
2011-05-31    243.310904
2011-06-30    199.899561
2011-07-31    211.396840
2011-08-31    228.967043
2011-09-30    256.004789
2011-10-31    254.997669
2011-11-30    254.091350
2011-12-31    248.552008
2012-01-31    285.951095
2012-02-29    270.462575
2012-03-31    271.924473
2012-04-30    234.889476
2012-05-31    226.517097
2012-06-30    201.333878
2012-07-31    194.101332
2012-08-31    229.655726
2012-09-30    246.372618
2012-10-31    242.692292
2012-11-30    208.849583
2012-12-31    200.924310
2013-01-31    208.435636
2013-02-28    243.015961
2013-03-31    287.352039
2013-04-30    292.060316
2013-05-31    285.716369
2013-06-30    232.889042
2013-07-31    213.093185
2013-08-31    199.255632
2013-09-30    199.681676
2013-10-31    199.116893
2013-11-30    202.230471
2013-12-31    234.276635
2014-01-31    260.267393
2014-02-28    270.719732
2014-03-31    257.455065
2014-04-30    227.882683
2014-05-31    199.698703
2014-06-30    185.316039
2014-07-31    190.174256
2014-08-31    228.571611
2014-09-30    232.785327
2014-10-31    250.405744
2014-11-30    228.357550
2014-12-31    213.951551
Freq: ME, Name: Sales, dtype: float64

In [93]:
# Find the correlation matrix between `Sales`, `Quantity`, `Discount`, and `Profit`
df[['Sales','Quantity','Discount','Profit']].corr()

             Sales  Quantity  Discount    Profit
Sales     1.000000  0.200795 -0.028190  0.755940
Quantity  0.200795  1.000000  0.008623  0.124908
Discount -0.028190  0.008623  1.000000 -0.113502
Profit    0.755940  0.124908 -0.113502  1.000000

In [94]:
# Use `.rank()` to rank customers by total sales within each region.
df['Rank']=df.groupby('Region')['Sales'].rank(ascending=False)

In [95]:
# Identify the top 10% of orders by Sales using `.quantile()`.
threshold=df['Sales'].quantile(0.9); df[df['Sales']>=threshold]

,Row ID,Order ID,Year,Order Date,Ship Date,ShipMode,Customer ID,Customer Name,Segment,Country,...,Order_Month,Ship_Weekday,Shipping_Days,Category_Total_Sales,Sales_Bin,Profit_Quartile,Profit_Category,Segment_Code,Discount_Flag,Rank
1,2,CA-2013-152156,2013,2013-09-11,NaN,Second Class,CG-12520,CLAIRE GUTE,Consumer,United States,...,9,NaN,NaN,741999.7953,Low,"(29.364, 8399.976]",High,0,Normal,118.0
3,4,US-2012-108966,2012,2012-11-10,10/18/2012,Standard Class,SO-20335,SEAN O'DONNELL,Consumer,United States,...,11,Thursday,-23.0,741999.7953,Low,"(-0.001, 1.729]",Low,0,Heavy Discount,87.0
7,8,CA-2011-115812,2011,2011-09-06,6/14/2011,Standard Class,BH-11710,BROSINA HOFFMAN,Consumer,United States,...,9,Tuesday,-84.0,836154.0330,Low,"(29.364, 8399.976]",High,0,Normal,176.0
10,11,CA-2011-115812,2011,2011-09-06,6/14/2011,Standard Class,BH-11710,BROSINA HOFFMAN,Consumer,United States,...,9,Tuesday,-84.0,741999.7953,Low,"(29.364, 8399.976]",High,0,Normal,53.0
11,12,CA-2011-115812,2011,2011-09-06,6/14/2011,Standard Class,BH-11710,BROSINA HOFFMAN,Consumer,United States,...,9,Tuesday,-84.0,836154.0330,Low,"(29.364, 8399.976]",High,0,Normal,175.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9931,9932,CA-2012-104948,2012,2012-11-13,11/17/2012,Standard Class,KH-16510,KEITH HERRERA,Consumer,United States,...,11,Saturday,4.0,741999.7953,Low,"(-0.001, 1.729]",Low,0,Normal,259.0
9942,9943,CA-2011-143371,2011,2011-12-28,NaN,Standard Class,MD-17350,MARIBETH DONA,Consumer,United States,...,12,NaN,NaN,719047.0320,Low,"(29.364, 8399.976]",Low,0,Normal,161.0
9947,9948,CA-2014-121559,2014,2014-02-06,NaN,Second Class,HW-14935,HELEN WASSERMAN,Corporate,United States,...,2,NaN,NaN,741999.7953,Low,"(29.364, 8399.976]",High,1,Normal,32.0
9948,9949,CA-2014-121559,2014,2014-02-06,NaN,Second Class,HW-14935,HELEN WASSERMAN,Corporate,United States,...,2,NaN,NaN,719047.0320,Low,"(29.364, 8399.976]",High,1,Normal,21.0
9968,9969,CA-2014-153871,2014,2014-12-12,12/18/2014,Standard Class,RB-19435,RICHARD BIERNER,Consumer,United States,...,12,Thursday,6.0,719047.0320,Low,"(29.364, 8399.976]",High,0,Normal,216.0

In [96]:
# Use `pd.get_dummies()` to one-hot encode the `Ship Mode` column.
pd.get_dummies(df,columns=['ShipMode'])

,Row ID,Order ID,Year,Order Date,Ship Date,Customer ID,Customer Name,Segment,Country,City,...,Sales_Bin,Profit_Quartile,Profit_Category,Segment_Code,Discount_Flag,Rank,ShipMode_First Class,ShipMode_Same Day,ShipMode_Second Class,ShipMode_Standard Class
0,1,CA-2013-152156,2013,2013-09-11,NaN,CG-12520,CLAIRE GUTE,Consumer,United States,Henderson,...,Low,"(29.364, 8399.976]",Low,0,Normal,344.0,False,False,True,False
1,2,CA-2013-152156,2013,2013-09-11,NaN,CG-12520,CLAIRE GUTE,Consumer,United States,Henderson,...,Low,"(29.364, 8399.976]",High,0,Normal,118.0,False,False,True,False
2,3,CA-2013-138688,2013,2013-06-13,6/17/2013,DV-13045,DARRIN VAN HUFF,Corporate,United States,Los Angeles,...,Low,"(1.729, 8.666]",Low,1,Normal,2596.5,False,False,True,False
3,4,US-2012-108966,2012,2012-11-10,10/18/2012,SO-20335,SEAN O'DONNELL,Consumer,United States,Fort Lauderdale,...,Low,"(-0.001, 1.729]",Low,0,Heavy Discount,87.0,False,False,False,True
4,5,US-2012-108966,2012,2012-11-10,10/18/2012,SO-20335,SEAN O'DONNELL,Consumer,United States,Fort Lauderdale,...,Low,"(1.729, 8.666]",Low,0,Normal,1124.0,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2011-110422,2011,2011-01-22,1/24/2011,TB-21400,TOM BOECKENHAUER,Consumer,United States,Miami,...,Low,"(1.729, 8.666]",Low,0,Normal,1081.0,False,False,True,False
9990,9991,CA-2014-121258,2014,2014-02-27,NaN,DB-13060,DAVE BROOKS,Consumer,United States,Costa Mesa,...,Low,"(8.666, 29.364]",Low,0,Normal,1327.5,False,False,False,True
9991,9992,CA-2014-121258,2014,2014-02-27,NaN,DB-13060,DAVE BROOKS,Consumer,United States,Costa Mesa,...,Low,"(8.666, 29.364]",Low,0,Normal,687.5,False,False,False,True
9992,9993,CA-2014-121258,2014,2014-02-27,NaN,DB-13060,DAVE BROOKS,Consumer,United States,Costa Mesa,...,Low,"(8.666, 29.364]",Low,0,Normal,2119.0,False,False,False,True
9993,9994,CA-2014-119914,2014,2014-05-05,NaN,CC-12220,CHRIS CORTES,Consumer,United States,Westminster,...,Low,"(29.364, 8399.976]",High,0,Normal,717.0,False,False,True,False

In [97]:
# Calculate the cumulative sum of `Sales` sorted by `Order Date`.
df.sort_values('Order Date')['Sales'].cumsum()

3365    2.906660e+02
157     7.482340e+02
8309    8.855860e+02
7949    9.491380e+02
7947    9.679780e+02
            ...
907     2.297110e+06
1296    2.297124e+06
1297    2.297145e+06
908     2.297198e+06
5091    2.297201e+06
Name: Sales, Length: 9994, dtype: float64

In [98]:
# Use `.pipe()` to chain two custom functions: one that adds 'Shipping_Days' and one that adds 'Profit_Margin'.
def add_shipping(df):
    df['Shipping_Days']=(pd.to_datetime(df['Ship Date'])-df['Order Date']).dt.days
    return df

def add_margin(df):
    df['Profit_Margin']=df['Profit']/df['Sales']
    return df

df.pipe(add_shipping).pipe(add_margin)

,Row ID,Order ID,Year,Order Date,Ship Date,ShipMode,Customer ID,Customer Name,Segment,Country,...,Ship_Weekday,Shipping_Days,Category_Total_Sales,Sales_Bin,Profit_Quartile,Profit_Category,Segment_Code,Discount_Flag,Rank,Profit_Margin
0,1,CA-2013-152156,2013,2013-09-11,NaN,Second Class,CG-12520,CLAIRE GUTE,Consumer,United States,...,NaN,NaN,741999.7953,Low,"(29.364, 8399.976]",Low,0,Normal,344.0,0.1600
1,2,CA-2013-152156,2013,2013-09-11,NaN,Second Class,CG-12520,CLAIRE GUTE,Consumer,United States,...,NaN,NaN,741999.7953,Low,"(29.364, 8399.976]",High,0,Normal,118.0,0.3000
2,3,CA-2013-138688,2013,2013-06-13,6/17/2013,Second Class,DV-13045,DARRIN VAN HUFF,Corporate,United States,...,Monday,4.0,719047.0320,Low,"(1.729, 8.666]",Low,1,Normal,2596.5,0.4700
3,4,US-2012-108966,2012,2012-11-10,10/18/2012,Standard Class,SO-20335,SEAN O'DONNELL,Consumer,United States,...,Thursday,-23.0,741999.7953,Low,"(-0.001, 1.729]",Low,0,Heavy Discount,87.0,0.0000
4,5,US-2012-108966,2012,2012-11-10,10/18/2012,Standard Class,SO-20335,SEAN O'DONNELL,Consumer,United States,...,Thursday,-23.0,719047.0320,Low,"(1.729, 8.666]",Low,0,Normal,1124.0,0.1125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2011-110422,2011,2011-01-22,1/24/2011,Second Class,TB-21400,TOM BOECKENHAUER,Consumer,United States,...,Monday,2.0,741999.7953,Low,"(1.729, 8.666]",Low,0,Normal,1081.0,0.1625
9990,9991,CA-2014-121258,2014,2014-02-27,NaN,Standard Class,DB-13060,DAVE BROOKS,Consumer,United States,...,NaN,NaN,741999.7953,Low,"(8.666, 29.364]",Low,0,Normal,1327.5,0.1700
9991,9992,CA-2014-121258,2014,2014-02-27,NaN,Standard Class,DB-13060,DAVE BROOKS,Consumer,United States,...,NaN,NaN,836154.0330,Low,"(8.666, 29.364]",Low,0,Normal,687.5,0.0750
9992,9993,CA-2014-121258,2014,2014-02-27,NaN,Standard Class,DB-13060,DAVE BROOKS,Consumer,United States,...,NaN,NaN,719047.0320,Low,"(8.666, 29.364]",Low,0,Normal,2119.0,0.4500
9993,9994,CA-2014-119914,2014,2014-05-05,NaN,Second Class,CC-12220,CHRIS CORTES,Consumer,United States,...,NaN,NaN,719047.0320,Low,"(29.364, 8399.976]",High,0,Normal,717.0,0.3000

In [99]:
# Detect outliers in `Sales` using the IQR method (Q1 - 1.5×IQR and Q3 + 1.5×IQR).
Q1=df['Sales'].quantile(0.25); Q3=df['Sales'].quantile(0.75); IQR=Q3-Q1; df[(df['Sales']<Q1-1.5*IQR)|(df['Sales']>Q3+1.5*IQR)]

,Row ID,Order ID,Year,Order Date,Ship Date,ShipMode,Customer ID,Customer Name,Segment,Country,...,Order_Month,Ship_Weekday,Shipping_Days,Category_Total_Sales,Sales_Bin,Profit_Quartile,Profit_Category,Segment_Code,Discount_Flag,Rank
1,2,CA-2013-152156,2013,2013-09-11,NaN,Second Class,CG-12520,CLAIRE GUTE,Consumer,United States,...,9,NaN,NaN,741999.7953,Low,"(29.364, 8399.976]",High,0,Normal,118.0
3,4,US-2012-108966,2012,2012-11-10,10/18/2012,Standard Class,SO-20335,SEAN O'DONNELL,Consumer,United States,...,11,Thursday,-23.0,741999.7953,Low,"(-0.001, 1.729]",Low,0,Heavy Discount,87.0
7,8,CA-2011-115812,2011,2011-09-06,6/14/2011,Standard Class,BH-11710,BROSINA HOFFMAN,Consumer,United States,...,9,Tuesday,-84.0,836154.0330,Low,"(29.364, 8399.976]",High,0,Normal,176.0
10,11,CA-2011-115812,2011,2011-09-06,6/14/2011,Standard Class,BH-11710,BROSINA HOFFMAN,Consumer,United States,...,9,Tuesday,-84.0,741999.7953,Low,"(29.364, 8399.976]",High,0,Normal,53.0
11,12,CA-2011-115812,2011,2011-09-06,6/14/2011,Standard Class,BH-11710,BROSINA HOFFMAN,Consumer,United States,...,9,Tuesday,-84.0,836154.0330,Low,"(29.364, 8399.976]",High,0,Normal,175.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9931,9932,CA-2012-104948,2012,2012-11-13,11/17/2012,Standard Class,KH-16510,KEITH HERRERA,Consumer,United States,...,11,Saturday,4.0,741999.7953,Low,"(-0.001, 1.729]",Low,0,Normal,259.0
9942,9943,CA-2011-143371,2011,2011-12-28,NaN,Standard Class,MD-17350,MARIBETH DONA,Consumer,United States,...,12,NaN,NaN,719047.0320,Low,"(29.364, 8399.976]",Low,0,Normal,161.0
9947,9948,CA-2014-121559,2014,2014-02-06,NaN,Second Class,HW-14935,HELEN WASSERMAN,Corporate,United States,...,2,NaN,NaN,741999.7953,Low,"(29.364, 8399.976]",High,1,Normal,32.0
9948,9949,CA-2014-121559,2014,2014-02-06,NaN,Second Class,HW-14935,HELEN WASSERMAN,Corporate,United States,...,2,NaN,NaN,719047.0320,Low,"(29.364, 8399.976]",High,1,Normal,21.0
9968,9969,CA-2014-153871,2014,2014-12-12,12/18/2014,Standard Class,RB-19435,RICHARD BIERNER,Consumer,United States,...,12,Thursday,6.0,719047.0320,Low,"(29.364, 8399.976]",High,0,Normal,216.0

In [100]:
# Use `itertools.groupby` equivalent in pandas to find consecutive same-day orders.
df['Same_Day_Group']=(df['Order Date'].diff()!=pd.Timedelta(0)).cumsum()

In [101]:
# Create a multi-level column DataFrame by grouping on Region and computing multiple aggregations on Sales and Profit.
df.groupby('Region').agg({'Sales':['sum','mean'],'Profit':['sum','mean']})

               Sales                   Profit
                 sum        mean          sum       mean
Region
Central  501239.8908  215.772661   96021.2475  41.335018
East     678781.2400  238.336110  141113.3875  49.548240
South    391721.9050  241.803645   74254.2626  45.835965
West     725457.8245  226.493233  131139.4098  40.942682

# Performance

In [102]:
# Set `Order ID` as the DataFrame index and verify the change.
df.set_index('Order ID',inplace=True)

In [103]:
# Use `.query()` method to filter rows where Sales > 500 and Region == 'East'.
df.query("Sales > 500 and Region == 'East'")

,Row ID,Year,Order Date,Ship Date,ShipMode,Customer ID,Customer Name,Segment,Country,City,...,Ship_Weekday,Shipping_Days,Category_Total_Sales,Sales_Bin,Profit_Quartile,Profit_Category,Segment_Code,Discount_Flag,Rank,Same_Day_Group
Order ID,,,,,,,,,,,,,,,,,,,,,
US-2012-150630,28,2012,2012-09-17,9/21/2012,Standard Class,TB-21520,TRACY BLUMSTEIN,Consumer,United States,Philadelphia,...,Friday,4.0,741999.7953,Low,"(-0.001, 1.729]",Low,0,Heavy Discount,23.0,15
CA-2013-105816,55,2013,2013-12-12,12/18/2013,Standard Class,JM-15265,JANET MOLINARI,Corporate,United States,New York City,...,Wednesday,6.0,836154.0330,Low,"(29.364, 8399.976]",High,1,Normal,138.0,26
CA-2012-102281,190,2012,2012-12-10,10/14/2012,First Class,MP-17470,MARK PACKER,Home_Office,United States,New York City,...,Sunday,-57.0,741999.7953,Low,"(29.364, 8399.976]",High,2,Normal,163.0,93
CA-2012-102281,193,2012,2012-12-10,10/14/2012,First Class,MP-17470,MARK PACKER,Home_Office,United States,New York City,...,Sunday,-57.0,741999.7953,Low,"(29.364, 8399.976]",Low,2,Normal,264.0,93
CA-2012-146262,216,2012,2012-02-01,NaN,Standard Class,VW-21775,VICTORIA WILSON,Corporate,United States,Medina,...,NaN,NaN,836154.0330,Low,"(-0.001, 1.729]",Low,1,Heavy Discount,110.0,105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
US-2012-116981,9867,2012,2012-03-26,3/28/2012,Second Class,SM-20950,SUZANNE MCNAIR,Corporate,United States,New York City,...,Wednesday,2.0,719047.0320,Low,"(29.364, 8399.976]",High,1,Normal,121.5,4940
US-2014-166324,9877,2014,2014-04-21,4/22/2014,First Class,BE-11455,BRAD EASON,Home_Office,United States,Cleveland,...,Tuesday,1.0,719047.0320,Low,"(-0.001, 1.729]",Low,2,Normal,183.0,4946
CA-2013-122581,9880,2013,2013-08-22,8/26/2013,Standard Class,JK-15370,JAY KIMMEL,Consumer,United States,New York City,...,Monday,4.0,741999.7953,Low,"(29.364, 8399.976]",High,0,Normal,290.0,4947
CA-2012-159534,9926,2012,2012-03-20,3/23/2012,First Class,DH-13075,DAVE HALLSTEN,Corporate,United States,New York City,...,Friday,3.0,719047.0320,Low,"(29.364, 8399.976]",High,1,Normal,120.0,4970
CA-2014-153871,9969,2014,2014-12-12,12/18/2014,Standard Class,RB-19435,RICHARD BIERNER,Consumer,United States,Plainfield,...,Thursday,6.0,719047.0320,Low,"(29.364, 8399.976]",High,0,Normal,216.0,4990

In [104]:
# Use categorical dtype for `Category`, `Segment`, and `Region` columns to save memory.
df[['Category','Segment','Region']]=df[['Category','Segment','Region']].astype('category')

In [105]:
# Compare memory usage before and after converting to categorical dtype.
df.memory_usage(deep=True)

Index                   893854
Row ID                   79952
Year                    529682
Order Date               79952
Ship Date               481034
ShipMode                617860
Customer ID             569658
Customer Name           620659
Segment                  10169
Country                 619628
City                    582957
State                   574527
Postal Code              79952
Region                   10210
Product ID              639616
Category                 10175
SubCategory             561580
Product Name            863390
Sales                    79952
Quantity                 79952
Discount                 79952
Profit                   79952
Avg_Category_Sales       79952
Order_Prefix            509694
First_Name              542547
Last_Name               557696
Product_Name_Length      79952
Order_Month              39976
Ship_Weekday            467370
Shipping_Days            79952
Category_Total_Sales     79952
Sales_Bin                10384
Profit_Quartile          10058
Profit_Category         521416
Segment_Code             79952
Discount_Flag           558998
Rank                     79952
Same_Day_Group           79952
dtype: int64

In [1]:
# Use `chunksize` to read the Excel file in chunks of 1000 rows via CSV export first
import pandas as pd

In [2]:
chunk_size = 1000

In [3]:
for chunk in pd.read_csv(r"C:\Users\mingm\Videos\sample_large_dataset.csv", chunksize=chunk_size):
    print(chunk.head())   
    print("Chunk Shape:", chunk.shape)

   ID    Name  Age       City
0   1  User_1   21  Kathmandu
1   2  User_2   22  Kathmandu
2   3  User_3   23  Kathmandu
3   4  User_4   24  Kathmandu
4   5  User_5   25  Kathmandu
Chunk Shape: (1000, 4)
        ID       Name  Age       City
1000  1001  User_1001   31  Kathmandu
1001  1002  User_1002   32  Kathmandu
1002  1003  User_1003   33  Kathmandu
1003  1004  User_1004   34  Kathmandu
1004  1005  User_1005   35  Kathmandu
Chunk Shape: (1000, 4)
        ID       Name  Age       City
2000  2001  User_2001   41  Kathmandu
2001  2002  User_2002   42  Kathmandu
2002  2003  User_2003   43  Kathmandu
2003  2004  User_2004   44  Kathmandu
2004  2005  User_2005   45  Kathmandu
Chunk Shape: (1000, 4)
        ID       Name  Age       City
3000  3001  User_3001   21  Kathmandu
3001  3002  User_3002   22  Kathmandu
3002  3003  User_3003   23  Kathmandu
3003  3004  User_3004   24  Kathmandu
3004  3005  User_3005   25  Kathmandu
Chunk Shape: (1000, 4)
        ID       Name  Age       City
4000  4001  User_4001   31  Kathmandu
4001  4002  User_4002   32  Kathmandu
4002  4003  User_4003   33  Kathmandu
4003  4004  User_4004   34  Kathmandu
4004  4005  User_4005   35  Kathmandu
Chunk Shape: (1000, 4)
        ID       Name  Age       City
5000  5001  User_5001   41  Kathmandu
5001  5002  User_5002   42  Kathmandu
5002  5003  User_5003   43  Kathmandu
5003  5004  User_5004   44  Kathmandu
5004  5005  User_5005   45  Kathmandu
Chunk Shape: (1000, 4)
        ID       Name  Age       City
6000  6001  User_6001   21  Kathmandu
6001  6002  User_6002   22  Kathmandu
6002  6003  User_6003   23  Kathmandu
6003  6004  User_6004   24  Kathmandu
6004  6005  User_6005   25  Kathmandu
Chunk Shape: (1000, 4)
        ID       Name  Age       City
7000  7001  User_7001   31  Kathmandu
7001  7002  User_7002   32  Kathmandu
7002  7003  User_7003   33  Kathmandu
7003  7004  User_7004   34  Kathmandu
7004  7005  User_7005   35  Kathmandu
Chunk Shape: (1000, 4)
        ID       Name  Age       City
8000  8001  User_8001   41  Kathmandu
8001  8002  User_8002   42  Kathmandu
8002  8003  User_8003   43  Kathmandu
8003  8004  User_8004   44  Kathmandu
8004  8005  User_8005   45  Kathmandu
Chunk Shape: (1000, 4)
        ID       Name  Age       City
9000  9001  User_9001   21  Kathmandu
9001  9002  User_9002   22  Kathmandu
9002  9003  User_9003   23  Kathmandu
9003  9004  User_9004   24  Kathmandu
9004  9005  User_9005   25  Kathmandu
Chunk Shape: (1000, 4)

In [7]:
# Export the top 10 customers by Sales to a new Excel file with formatting
import pandas as pd

df = pd.read_excel(r"C:\Users\mingm\Videos\top_10_customers.xlsx")

top10 = df.sort_values("Sales", ascending=False).head(10)

top10.to_excel("top_10_customers_new.xlsx", index=False)