# Pandas

Series and DataFrames
Loading datasets (CSV, Excel)
Exploring data (head, info, describe)
Indexing & Filtering
Sorting Data

In [1]:
# install pandas 
!pip install pandas

Requirement already satisfied: pandas in d:\codeit_python\venv\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in d:\codeit_python\venv\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\codeit_python\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\codeit_python\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in d:\codeit_python\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# import pandas 
import pandas as pd

# Pandas Data Structures 
a) series b) DataFrame c) Panel 
series very similar to one D Arrayy , decalred with pd.Series() 
DataFrame is very similar to  2 D array , declared with pd.DataFrame() 
Panel is very similar to 3 D Array  declaed with pd.Panel()

In [4]:
# Series has no conecpt  of row and col , data are indexed 
pd.Series(range(2,45,3))

0      2
1      5
2      8
3     11
4     14
5     17
6     20
7     23
8     26
9     29
10    32
11    35
12    38
13    41
14    44
dtype: int64

In [5]:
# pd.DataFrame() , col name , row nummber
pd.DataFrame(range(2,45,3))

     0
0    2
1    5
2    8
3   11
4   14
5   17
6   20
7   23
8   26
9   29
10  32
11  35
12  38
13  41
14  44

every file we load in to pandas are stored as dataframe, 
dataframe are data structures in pandas use to store data in matrix of row and column . Similary to variable they store data temporarily

# Loading Data

In [ ]:
# loading CSV File 
# Syntax 
pd.read_csv(r"file_path")

In [120]:
data = pd.read_csv(r"C:\Users\Lenovo\Desktop\used_cars_data_uncleaned.csv")

In [121]:
data.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,Good Mileage,Maruti,Wagon
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,Nice Mileage,Hyundai,Creta
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.50,Nice Mileage,Honda,Jazz
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00,Good Mileage,Maruti,Ertiga
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74,Nice Mileage,Audi,A4

In [ ]:
# Read / Load Excel File 
# SYntax 
pd.read_excel(r"file_path")

In [9]:
data_excel =pd.read_excel(r"C:\Users\Lenovo\Desktop\mixed\data_only.xlsx")
data_excel.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Art,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Customer ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer Name,Segment,Country,City,...,Region Code,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Total Sales
3,AA-10315,CA-2011-128055,2011,2011-03-31 00:00:00,2011-04-05 00:00:00,Standard Class,Alex Avila,Consumer,United States,San Francisco,...,2,OFF-BI-10004390,Office Supplies,Binders,GBC DocuBind 200 Manual Binding Machine,673.568,2,0.2,252.588,1347.136
4,AA-10315,CA-2011-128055,2011,2011-03-31 00:00:00,2011-04-05 00:00:00,Standard Class,Alex Avila,Consumer,United States,San Francisco,...,2,OFF-AP-10002765,Office Supplies,Appliances,Fellowes Advanced Computer Series Surge Protec...,52.98,2,0,14.8344,105.96

# Preview the Data

In [ ]:
Exploring data (head, info, describe)

In [10]:
# head() 
# tail() 
# info() 
# describe() 
# shape ()
# columns

In [11]:
# head() returns first five rows 
data.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,Good Mileage,Maruti,Wagon
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,Nice Mileage,Hyundai,Creta
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.50,Nice Mileage,Honda,Jazz
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00,Good Mileage,Maruti,Ertiga
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74,Nice Mileage,Audi,A4

In [12]:
# head(2) returns first 2 rows 
data.head(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,Good Mileage,Maruti,Wagon
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,Nice Mileage,Hyundai,Creta

In [13]:
# tail() returns last 5 rows of the dataset 
data.tail()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
5839,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.40,1248.0,74.0,5.0,4.75,Good Mileage,Maruti,Swift
5840,6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.40,1120.0,71.0,5.0,4.00,Good Mileage,Hyundai,Xcent
5841,6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.00,2498.0,112.0,8.0,2.90,Nice Mileage,Mahindra,Xylo
5842,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.90,998.0,67.1,5.0,2.65,Nice Mileage,Maruti,Wagon
5843,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936.0,57.6,5.0,2.50,Good Mileage,Chevrolet,Beat

In [15]:
data.tail(2) # returns last 2 rows of the dataset

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
5842,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.90,998.0,67.1,5.0,2.65,Nice Mileage,Maruti,Wagon
5843,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936.0,57.6,5.0,2.50,Good Mileage,Chevrolet,Beat

In [16]:
# info() returs column name, their data type and non-null count , memory useages 
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5844 entries, 0 to 5843
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              5844 non-null   int64
 1   Name               5844 non-null   str
 2   Location           5844 non-null   str
 3   Year               5844 non-null   int64
 4   Kilometers_Driven  5844 non-null   int64
 5   Fuel_Type          5844 non-null   str
 6   Transmission       5844 non-null   str
 7   Owner_Type         5844 non-null   str
 8   Mileage            5844 non-null   float64
 9   Engine             5844 non-null   float64
 10  Power              5844 non-null   float64
 11  Seats              5844 non-null   float64
 12  Price              5844 non-null   float64
 13  mileage_type       5844 non-null   str
 14  brand              5844 non-null   str
 15  model              5844 non-null   str
dtypes: float64(5), int64(3), str(8)
memory usage: 730.6 KB

In [17]:
# describe()  retursn basic maths and stats calcuations of numeric data columns 
data.describe()

,S.No.,Year,Kilometers_Driven,Mileage,Engine,Power,Seats,Price
count,5844.000000,5844.000000,5.844000e+03,5844.000000,5844.000000,5844.000000,5844.000000,5844.000000
mean,3012.966290,2013.481006,5.832696e+04,18.365412,1622.834531,113.139612,5.285079,9.545515
std,1736.228205,3.163546,9.235508e+04,4.188280,598.989657,53.812210,0.806768,11.187139
min,0.000000,1998.000000,1.710000e+02,6.400000,624.000000,34.200000,2.000000,0.440000
25%,1512.750000,2012.000000,3.349325e+04,15.300000,1198.000000,75.000000,5.000000,3.517500
50%,3013.500000,2014.000000,5.256450e+04,18.330000,1495.000000,94.680000,5.000000,5.705000
75%,4514.250000,2016.000000,7.241450e+04,21.100000,1984.000000,138.100000,5.000000,10.000000
max,6018.000000,2019.000000,6.500000e+06,33.540000,5998.000000,560.000000,10.000000,160.000000

In [18]:
# shape returns number of row and column in form of tuple 
data.shape

(5844, 16)

In [19]:
# columns , returns name of columns in form of list 
data.columns

Index(['S.No.', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'Price', 'mileage_type', 'brand', 'model'],
      dtype='str')

# Indexing & Filtering

In [23]:
data.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,Good Mileage,Maruti,Wagon
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,Nice Mileage,Hyundai,Creta
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.50,Nice Mileage,Honda,Jazz
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00,Good Mileage,Maruti,Ertiga
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74,Nice Mileage,Audi,A4

In [24]:
# Indexing is the process of selecting data using row number and colum (name or index)

In [25]:
# selecting a single column 
data['Year']

0       2010
1       2015
2       2011
3       2012
4       2013
        ...
5839    2014
5840    2015
5841    2012
5842    2013
5843    2011
Name: Year, Length: 5844, dtype: int64

In [27]:
# select multiple columns , 'year', 'transmission'
data[['Year', 'Transmission']]

      Year Transmission
0     2010       Manual
1     2015       Manual
2     2011       Manual
3     2012       Manual
4     2013    Automatic
...    ...          ...
5839  2014       Manual
5840  2015       Manual
5841  2012       Manual
5842  2013       Manual
5843  2011       Manual

[5844 rows x 2 columns]

In [30]:
# loc() 
data.loc[0:10,'Year']

0     2010
1     2015
2     2011
3     2012
4     2013
5     2012
6     2013
7     2016
8     2013
9     2012
10    2018
Name: Year, dtype: int64

In [31]:
# select columns 'Year'  and 'Transmission' using loc() 
data.loc[:, ['Year', 'Transmission']]

      Year Transmission
0     2010       Manual
1     2015       Manual
2     2011       Manual
3     2012       Manual
4     2013    Automatic
...    ...          ...
5839  2014       Manual
5840  2015       Manual
5841  2012       Manual
5842  2013       Manual
5843  2011       Manual

[5844 rows x 2 columns]

In [32]:
# Selecting rows 
#  sample() select randomly  , selects 20 rows randomly 
data.sample(n=20)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
5792,5964,Hyundai Verna VTVT 1.6 AT SX Option,Mumbai,2018,8000,Petrol,Automatic,First,17.00,1591.0,121.30,5.0,12.85,Nice Mileage,Hyundai,Verna
4310,4441,Audi Q7 3.0 TDI Quattro Technology,Hyderabad,2014,60000,Diesel,Automatic,First,12.07,2967.0,241.40,7.0,45.00,Nice Mileage,Audi,Q7
722,752,Mercedes-Benz E-Class 2015-2017 E250 Edition E,Kochi,2017,43368,Diesel,Automatic,First,15.00,2143.0,204.00,5.0,31.94,Nice Mileage,Mercedes-Benz,E-Class
392,408,Skoda Superb Elegance 1.8 TSI AT,Hyderabad,2010,57000,Petrol,Automatic,First,13.70,1798.0,157.75,5.0,7.25,Nice Mileage,Skoda,Superb
5353,5514,Volkswagen Vento 1.5 TDI Highline,Ahmedabad,2015,52123,Diesel,Manual,First,20.34,1498.0,103.20,5.0,7.50,Good Mileage,Volkswagen,Vento
3874,3994,Audi Q7 35 TDI Quattro Technology,Coimbatore,2016,32545,Diesel,Automatic,First,12.07,2967.0,241.40,7.0,48.76,Nice Mileage,Audi,Q7
5688,5854,Hyundai Grand i10 1.2 Kappa Sportz,Kochi,2016,28147,Petrol,Manual,First,18.90,1197.0,81.86,5.0,5.07,Nice Mileage,Hyundai,Grand
364,379,Maruti Ritz VDi,Hyderabad,2010,68000,Diesel,Manual,Second,21.10,1248.0,73.90,5.0,3.20,Good Mileage,Maruti,Ritz
1671,1727,Chevrolet Aveo U-VA 1.2 LS,Pune,2007,59000,Petrol,Manual,Third,15.26,1150.0,74.90,5.0,0.99,Nice Mileage,Chevrolet,Aveo
2055,2118,Mahindra XUV500 W10 2WD,Delhi,2015,62000,Diesel,Manual,First,16.00,2179.0,140.00,7.0,10.25,Nice Mileage,Mahindra,XUV500
1447,1499,Honda Accord VTi-L (AT),Mumbai,2007,80000,Petrol,Automatic,First,11.10,2354.0,142.00,5.0,3.00,Nice Mileage,Honda,Accord
1573,1627,Maruti Swift VDI BSIV,Ahmedabad,2017,49224,Diesel,Manual,First,25.20,1248.0,74.00,5.0,6.00,Good Mileage,Maruti,Swift
1527,1581,Volkswagen Jetta 2012-2014 2.0L TDI Comfortline,Mumbai,2012,78000,Diesel,Manual,First,19.33,1968.0,138.10,5.0,6.50,Nice Mileage,Volkswagen,Jetta
3405,3510,Hyundai Creta 1.6 SX Plus Petrol Automatic,Mumbai,2016,27000,Petrol,Automatic,First,13.00,1591.0,121.30,5.0,11.45,Nice Mileage,Hyundai,Creta
2971,3066,Audi A6 2011-2015 3.0 TDI Quattro Premium Plus,Pune,2012,50001,Diesel,Automatic,First,14.57,2967.0,241.38,5.0,29.00,Nice Mileage,Audi,A6
255,268,Maruti A-Star Vxi,Pune,2010,67000,Petrol,Manual,First,19.00,998.0,66.10,5.0,2.00,Nice Mileage,Maruti,A-Star
881,912,Maruti Eeco 7 Seater Standard,Coimbatore,2012,56661,Petrol,Manual,First,15.10,1196.0,73.00,7.0,3.61,Nice Mileage,Maruti,Eeco
427,446,Volkswagen Vento 1.6 Comfortline,Mumbai,2017,15000,Petrol,Manual,Second,16.09,1598.0,103.50,5.0,7.10,Nice Mileage,Volkswagen,Vento
4838,4986,Honda Amaze VX i-DTEC,Kolkata,2013,38001,Diesel,Manual,First,25.80,1498.0,98.60,5.0,3.90,Good Mileage,Honda,Amaze
4117,4244,Mahindra Scorpio 2009-2014 LX 2WD 7S,Mumbai,2014,84000,Diesel,Manual,First,12.05,2179.0,120.00,7.0,6.85,Nice Mileage,Mahindra,Scorpio

In [33]:
data.sample(frac=0.01) # selects 1 % of total  data randomly

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
2142,2207,Toyota Camry W4 (AT),Mumbai,2010,62714,Petrol,Automatic,First,12.10,2362.0,164.70,5.0,4.50,Nice Mileage,Toyota,Camry
1825,1883,Honda CR-V 2.4 MT,Chennai,2007,98000,Petrol,Manual,Second,10.80,2354.0,152.00,5.0,4.70,Nice Mileage,Honda,CR-V
5125,5281,Maruti Ertiga ZXI,Mumbai,2012,25000,Petrol,Manual,Second,17.50,1373.0,91.10,7.0,5.15,Nice Mileage,Maruti,Ertiga
5039,5193,Hyundai Grand i10 CRDi Magna,Hyderabad,2014,79000,Diesel,Manual,First,24.00,1120.0,70.00,5.0,4.15,Good Mileage,Hyundai,Grand
3073,3170,Chevrolet Cruze LTZ,Coimbatore,2014,80073,Diesel,Manual,First,17.30,1998.0,163.70,5.0,7.11,Nice Mileage,Chevrolet,Cruze
2832,2924,Land Rover Range Rover HSE Dynamic,Kochi,2018,41661,Diesel,Automatic,First,12.70,2179.0,187.70,5.0,44.83,Nice Mileage,Land,Rover
5492,5656,Honda City i DTEC V,Kochi,2016,84580,Diesel,Manual,First,26.00,1498.0,98.60,5.0,6.83,Good Mileage,Honda,City
3441,3550,Honda City i-DTEC ZX,Pune,2017,42000,Diesel,Manual,First,25.60,1498.0,98.60,5.0,12.00,Good Mileage,Honda,City
2589,2676,Hyundai Creta 1.6 CRDi SX,Kochi,2017,40459,Diesel,Manual,First,19.67,1582.0,126.20,5.0,13.28,Nice Mileage,Hyundai,Creta
2013,2075,Tata Zest Revotron 1.2T XMS,Chennai,2015,40000,Petrol,Manual,First,17.57,1193.0,88.70,5.0,4.00,Nice Mileage,Tata,Zest
2195,2260,BMW 5 Series 520d Luxury Line,Ahmedabad,2012,95000,Diesel,Automatic,Second,22.48,1995.0,190.00,5.0,17.50,Good Mileage,BMW,5
3855,3975,Mercedes-Benz E-Class 2009-2013 E250 CDI Elegance,Pune,2016,45000,Diesel,Automatic,First,14.21,2143.0,203.00,5.0,34.00,Nice Mileage,Mercedes-Benz,E-Class
778,808,Honda City 1.5 V MT Sunroof,Mumbai,2013,60669,Petrol,Manual,First,16.80,1497.0,116.30,5.0,4.95,Nice Mileage,Honda,City
136,142,Maruti Swift VVT VXI,Kochi,2016,34204,Petrol,Manual,First,22.00,1197.0,81.80,5.0,5.43,Good Mileage,Maruti,Swift
3183,3285,Hyundai Grand i10 Magna AT,Mumbai,2016,9000,Petrol,Automatic,First,18.90,1197.0,82.00,5.0,5.45,Nice Mileage,Hyundai,Grand
4889,5040,Maruti Versa DX2 BS II,Mumbai,2003,62000,Petrol,Manual,Second,11.30,1298.0,83.10,8.0,1.25,Nice Mileage,Maruti,Versa
3385,3490,Honda City i VTEC VX,Hyderabad,2016,36891,Petrol,Manual,First,17.80,1497.0,117.30,5.0,10.49,Nice Mileage,Honda,City
442,461,Renault Duster 110PS Diesel RxL,Hyderabad,2012,82749,Diesel,Manual,First,19.01,1461.0,108.45,5.0,5.99,Nice Mileage,Renault,Duster
1185,1225,Maruti 800 DX BSII,Jaipur,2009,32000,Petrol,Manual,First,16.10,796.0,37.00,4.0,0.90,Nice Mileage,Maruti,800
4881,5032,Hyundai i20 Active 1.4 SX,Hyderabad,2016,62679,Diesel,Manual,First,21.19,1396.0,88.73,5.0,6.95,Good Mileage,Hyundai,i20
350,365,Mini Clubman Cooper S,Pune,2017,8350,Petrol,Manual,First,13.80,1998.0,192.00,5.0,35.00,Nice Mileage,Mini,Clubman
1859,1918,Audi A4 2.0 TDI,Kochi,2013,45330,Diesel,Automatic,First,16.55,1968.0,147.51,5.0,13.19,Nice Mileage,Audi,A4
467,487,Hyundai Verna 1.6 SX,Kolkata,2013,37873,Diesel,Manual,First,22.32,1582.0,126.32,5.0,4.80,Good Mileage,Hyundai,Verna
5213,5370,Volkswagen Polo 1.2 MPI Comfortline,Mumbai,2014,15000,Petrol,Manual,First,16.47,1198.0,74.00,5.0,3.90,Nice Mileage,Volkswagen,Polo
4529,4664,Maruti Swift ZXI,Hyderabad,2011,53080,Petrol,Manual,First,18.60,1197.0,85.80,5.0,4.40,Nice Mileage,Maruti,Swift
3859,3979,Hyundai Grand i10 Asta,Kolkata,2015,15305,Petrol,Manual,First,18.90,1197.0,82.00,5.0,3.75,Nice Mileage,Hyundai,Grand
981,1017,Volkswagen Vento 1.5 TDI Comfortline,Coimbatore,2014,56658,Diesel,Manual,First,20.64,1498.0,108.50,5.0,5.39,Good Mileage,Volkswagen,Vento
4732,4875,Honda Civic 2006-2010 1.8 S MT,Delhi,2008,80000,Petrol,Manual,First,13.50,1799.0,130.00,5.0,2.75,Nice Mileage,Honda,Civic
596,618,Maruti Vitara Brezza ZDi,Pune,2016,21558,Diesel,Manual,First,24.30,1248.0,88.50,5.0,8.90,Good Mileage,Maruti,Vitara
2027,2089,BMW 6 Series 640d Coupe,Mumbai,2013,30000,Diesel,Automatic,First,9.52,2993.0,313.00,4.0,45.00,Not Good Mileage,BMW,6
1101,1139,Hyundai Grand i10 1.2 Kappa Magna,Delhi,2017,8471,Petrol,Manual,First,18.90,1197.0,81.86,5.0,5.00,Nice Mileage,Hyundai,Grand
3107,3205,Renault Duster 110PS Diesel RxZ,Coimbatore,2016,65257,Diesel,Manual,First,19.01,1461.0,108.45,5.0,9.75,Nice Mileage,Renault,Duster
4560,4696,Maruti Wagon R LX,Jaipur,2006,110000,Petrol,Manual,First,18.90,998.0,67.10,5.0,1.11,Nice Mileage,Maruti,Wagon
4963,5115,Maruti Swift VXI BSIII W/ ABS,Pune,2010,90246,Petrol,Manual,First,16.10,1298.0,88.20,5.0,2.95,Nice Mileage,Maruti,Swift
827,858,Honda Mobilio RS i DTEC,Chennai,2014,23000,Diesel,Manual,First,24.50,1498.0,98.60,7.0,6.90,Good Mileage,Honda,Mobilio
5565,5729,Skoda Superb Elegance 1.8 TSI AT,Pune,2010,71473,Petrol,Automatic,Second,13.70,1798.0,157.75,5.0,5.35,Nice Mileage,Skoda,Superb
5091,5246,Tata Indica V2 eLX,Pune,2017,49000,Diesel,Manual,Second,25.00,1396.0,69.00,5.0,1.60,Good Mileage,Tata,Indica
5320,5481,Chevrolet Cruze LTZ AT,Hyderabad,2011,78203,Diesel,Automatic,First,18.10,1991.0,147.90,4.0,5.50,Nice Mileage,Chevrolet,Cruze
1945,2005,Audi A4 2.0 TDI,Ahmedabad,2013,82002,Diesel,Automatic,Second,16.55,1968.0,147.51,5.0,17.50,Nice Mileage,Audi,A4
2596,2684,Skoda Laura 1.8 TSI Ambiente,Pune,2011,31900,Petrol,Manual,First,13.40,1798.0,157.80,5.0,3.75,Nice Mileage,Skoda,Laura
108,113,BMW 3 Series 320d Luxury Line,Mumbai,2015,56087,Diesel,Automatic,First,22.69,1995.0,190.00,5.0,20.75,Good Mileage,BMW,3
2621,2709,Honda Amaze V Petrol,Kochi,2016,40866,Petrol,Manual,First,19.50,1199.0,86.76,5.0,5.47,Nice Mileage,Honda,Amaze
5104,5259,Renault KWID RXT,Mumbai,2016,8554,Petrol,Manual,First,25.17,799.0,53.30,5.0,3.20,Good Mileage,Renault,KWID
363,378,Mercedes-Benz New C-Class 220,Chennai,2014,25000,Diesel,Manual,First,15.80,2148.0,170.00,5.0,26.00,Nice Mileage,Mercedes-Benz,New
1071,1109,Hyundai Verna 1.6 SX VTVT,Mumbai,2016,52001,Petrol,Manual,First,17.01,1591.0,121.30,5.0,6.45,Nice Mileage,Hyundai,Verna
3570,3684,Honda City i VTEC VX Option,Mumbai,2015,42366,Petrol,Manual,First,17.80,1497.0,117.30,5.0,7.75,Nice Mileage,Honda,City
670,695,Ford EcoSport 1.5 TDCi Titanium,Bangalore,2013,62084,Diesel,Manual,First,22.77,1498.0,98.59,5.0,6.60,Good Mileage,Ford,EcoSport
486,506,Mercedes-Benz S Class 2005 2013 S 350 CDI,Pune,2010,137000,Diesel,Automatic,First,13.50,2987.0,282.00,5.0,18.50,Nice Mileage,Mercedes-Benz,S
3776,3894,Toyota Innova 2.5 GX 7 STR,Hyderabad,2010,250000,Diesel,Manual,Second,12.80,2494.0,102.00,7.0,6.50,Nice Mileage,Toyota,Innova
2331,2405,Ford Figo 2015-2019 1.2P Titanium Opt MT,Coimbatore,2017,21740,Petrol,Manual,First,18.16,1196.0,86.80,5.0,6.42,Nice Mileage,Ford,Figo
289,302,Maruti Alto K10 LXI,Hyderabad,2011,70000,Petrol,Manual,First,20.92,998.0,67.10,5.0,2.10,Good Mileage,Maruti,Alto
2406,2482,Skoda Octavia Ambition 2.0 TDI AT,Bangalore,2013,58410,Diesel,Automatic,First,19.30,1968.0,141.00,5.0,14.50,Nice Mileage,Skoda,Octavia
3433,3542,Honda City 1.5 E MT,Jaipur,2009,86863,Petrol,Manual,First,17.00,1497.0,118.00,5.0,3.60,Nice Mileage,Honda,City
5086,5241,Ford EcoSport 1.5 Petrol Titanium,Hyderabad,2017,21800,Petrol,Manual,First,17.00,1497.0,121.36,5.0,8.75,Nice Mileage,Ford,EcoSport
5399,5562,Maruti Ciaz VDI SHVS,Kochi,2018,17804,Diesel,Manual,Second,28.09,1248.0,88.50,5.0,7.97,Good Mileage,Maruti,Ciaz
3528,3640,Toyota Fortuner 2.8 4WD MT,Kochi,2011,169006,Diesel,Manual,First,14.24,2755.0,174.50,7.0,10.64,Nice Mileage,Toyota,Fortuner
4070,4195,Hyundai i10 Era,Jaipur,2009,57000,Petrol,Manual,First,19.81,1086.0,68.05,5.0,2.25,Nice Mileage,Hyundai,i10
4905,5056,Ford Fiesta Diesel Trend,Bangalore,2011,47000,Diesel,Manual,Second,23.50,1498.0,90.00,5.0,6.00,Good Mileage,Ford,Fiesta

In [34]:
# select row indexn number 41 to 61 
data.iloc[41:62,:]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
41,42,Mahindra KUV 100 mFALCON D75 K8 Dual Tone,Coimbatore,2017,22033,Diesel,Manual,First,25.32,1198.0,77.00,6.0,5.58,Good Mileage,Mahindra,KUV
42,43,Hyundai i20 Magna Optional 1.2,Kochi,2014,35487,Petrol,Manual,First,18.50,1197.0,82.90,5.0,4.74,Nice Mileage,Hyundai,i20
43,44,Hyundai Elantra 2.0 SX Option AT,Bangalore,2014,46374,Petrol,Automatic,First,14.62,1999.0,149.92,5.0,8.85,Nice Mileage,Hyundai,Elantra
44,45,Toyota Corolla Altis G AT,Mumbai,2016,52001,Petrol,Automatic,First,14.28,1798.0,138.03,5.0,10.11,Nice Mileage,Toyota,Corolla
45,46,Hyundai Elantra CRDi,Ahmedabad,2008,58005,Diesel,Manual,Second,14.90,1991.0,112.20,5.0,4.25,Nice Mileage,Hyundai,Elantra
46,47,Toyota Innova Crysta 2.7 GX MT,Bangalore,2012,70704,Petrol,Manual,First,11.25,2694.0,163.70,7.0,10.95,Nice Mileage,Toyota,Innova
47,48,Hyundai Xcent 1.1 CRDi S,Jaipur,2014,75000,Diesel,Manual,First,24.40,1120.0,71.00,5.0,3.85,Good Mileage,Hyundai,Xcent
48,49,Mahindra Thar CRDe AC,Jaipur,2012,75800,Diesel,Manual,Second,16.55,2498.0,105.00,6.0,5.50,Nice Mileage,Mahindra,Thar
49,50,Audi A4 2.0 TDI 177 Bhp Premium Plus,Kochi,2015,13648,Diesel,Automatic,First,17.11,1968.0,174.33,5.0,21.43,Nice Mileage,Audi,A4
50,51,Maruti Swift LDI,Delhi,2014,52000,Diesel,Manual,First,22.90,1248.0,74.00,5.0,4.25,Good Mileage,Maruti,Swift
51,52,Maruti Swift Ldi BSIV,Kolkata,2014,53000,Diesel,Manual,First,17.80,1248.0,75.00,5.0,3.30,Nice Mileage,Maruti,Swift
52,53,Maruti Swift VDI,Delhi,2013,65650,Diesel,Manual,First,28.40,1248.0,74.00,5.0,3.85,Good Mileage,Maruti,Swift
53,54,Hyundai Grand i10 Sportz,Chennai,2015,54000,Petrol,Manual,Third,18.90,1197.0,82.00,5.0,3.60,Nice Mileage,Hyundai,Grand
54,55,Volkswagen Vento 2013-2015 1.6 Comfortline,Kolkata,2015,39000,Petrol,Manual,First,15.04,1598.0,103.20,5.0,3.99,Nice Mileage,Volkswagen,Vento
55,56,Renault KWID RXT,Kochi,2017,16542,Petrol,Manual,First,25.17,799.0,53.30,5.0,3.30,Good Mileage,Renault,KWID
56,57,Hyundai i10 Asta,Kolkata,2010,32000,Petrol,Manual,First,20.36,1197.0,78.90,5.0,2.07,Good Mileage,Hyundai,i10
57,58,Nissan X-Trail SLX AT,Hyderabad,2010,121812,Diesel,Automatic,First,13.29,1995.0,147.60,5.0,7.75,Nice Mileage,Nissan,X-Trail
58,59,Maruti Zen Estilo VXI BSIII,Hyderabad,2010,39300,Petrol,Manual,First,18.20,998.0,67.10,5.0,2.25,Nice Mileage,Maruti,Zen
59,60,Toyota Innova Crysta 2.4 GX MT 8S,Mumbai,2017,22000,Diesel,Manual,First,13.68,2393.0,147.80,8.0,16.50,Nice Mileage,Toyota,Innova
60,61,Ford Figo Diesel Titanium,Bangalore,2010,72000,Diesel,Manual,First,20.00,1399.0,68.00,5.0,2.75,Good Mileage,Ford,Figo
61,62,Mercedes-Benz New C-Class C 200 CGI Avantgarde,Delhi,2015,58000,Petrol,Automatic,First,11.74,1796.0,186.00,5.0,26.70,Nice Mileage,Mercedes-Benz,New

In [38]:
# select all rows in  index 10,99 in step 3 
data.iloc[10:100:3, 1:6]

,Name,Location,Year,Kilometers_Driven,Fuel_Type
10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol
13,Land Rover Range Rover 2.2L Pure,Delhi,2014,72000,Diesel
16,Maruti Swift DDiS VDI,Jaipur,2017,25000,Diesel
19,BMW 3 Series 320d,Kochi,2014,32982,Diesel
22,Hyundai i20 1.2 Magna,Kolkata,2010,45807,Petrol
25,Nissan Micra Diesel XV,Hyderabad,2012,54000,Diesel
28,Toyota Innova 2.5 V Diesel 7-seater,Mumbai,2007,262000,Diesel
31,Mahindra Ssangyong Rexton RX7,Bangalore,2013,72000,Diesel
34,Maruti Wagon R LXI BSIII,Jaipur,2009,83816,Petrol
37,Mercedes-Benz M-Class ML 350 CDI,Pune,2013,85000,Diesel
40,Tata Nano LX SE,Kochi,2014,19698,Petrol
43,Hyundai Elantra 2.0 SX Option AT,Bangalore,2014,46374,Petrol
46,Toyota Innova Crysta 2.7 GX MT,Bangalore,2012,70704,Petrol
49,Audi A4 2.0 TDI 177 Bhp Premium Plus,Kochi,2015,13648,Diesel
52,Maruti Swift VDI,Delhi,2013,65650,Diesel
55,Renault KWID RXT,Kochi,2017,16542,Petrol
58,Maruti Zen Estilo VXI BSIII,Hyderabad,2010,39300,Petrol
61,Mercedes-Benz New C-Class C 200 CGI Avantgarde,Delhi,2015,58000,Petrol
64,Audi A4 2.0 TDI Multitronic,Jaipur,2012,65664,Diesel
67,Hyundai Creta 1.4 E Plus Diesel,Mumbai,2018,13000,Diesel
70,Hyundai i10 Sportz 1.2 AT,Kochi,2012,45178,Petrol
73,Audi A6 2.0 TDI Design Edition,Delhi,2014,56000,Diesel
76,Maruti Swift VDI,Jaipur,2012,95100,Diesel
79,Ford Figo Diesel ZXI,Hyderabad,2012,70337,Diesel
82,BMW 5 Series 2003-2012 525d,Delhi,2011,75000,Diesel
85,Honda Amaze SX i-VTEC,Mumbai,2016,18949,Petrol
88,Ford Ecosport 1.5 DV5 MT Titanium Optional,Delhi,2013,57000,Diesel
91,Volkswagen Polo Diesel Highline 1.2L,Kolkata,2013,34212,Diesel
94,Volkswagen Polo Petrol Highline 1.6L,Delhi,2010,62001,Petrol
97,Datsun GO Plus T Petrol,Pune,2017,32851,Petrol

# Filter

In [39]:
# select data according to the condition 
data.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,Good Mileage,Maruti,Wagon
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,Nice Mileage,Hyundai,Creta
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.50,Nice Mileage,Honda,Jazz
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00,Good Mileage,Maruti,Ertiga
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74,Nice Mileage,Audi,A4

In [40]:
# select all the data where mileage is >=30
con =data['Mileage']>=30

In [41]:
data[con]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
1228,1269,Maruti Alto 800 2016-2019 CNG LXI,Mumbai,2018,10600,CNG,Manual,First,33.44,796.0,40.30,4.0,3.50,Excellent Mileage,Maruti,Alto
1286,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04,5.0,2.96,Excellent Mileage,Maruti,Wagon
1998,2059,Maruti Wagon R CNG LXI,Mumbai,2013,54000,CNG,Manual,First,33.54,998.0,67.04,5.0,3.05,Excellent Mileage,Maruti,Wagon
2298,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04,5.0,3.90,Excellent Mileage,Maruti,Wagon
2613,2701,Maruti Celerio CNG VXI MT,Kochi,2016,70536,CNG,Manual,First,31.79,998.0,58.33,5.0,4.58,Excellent Mileage,Maruti,Celerio
3022,3119,Maruti Alto K10 LXI CNG Optional,Kochi,2018,44202,CNG,Manual,First,32.26,998.0,58.20,4.0,4.00,Excellent Mileage,Maruti,Alto
3032,3129,Maruti Wagon R CNG LXI,Delhi,2014,74663,CNG,Manual,First,33.54,998.0,67.04,5.0,3.25,Excellent Mileage,Maruti,Wagon
3444,3553,Maruti Alto 800 2016-2019 CNG LXI,Pune,2015,18000,CNG,Manual,First,33.44,796.0,40.30,4.0,3.00,Excellent Mileage,Maruti,Alto
3752,3869,Maruti Alto 800 2016-2019 CNG LXI,Delhi,2012,65537,CNG,Manual,Second,33.44,796.0,40.30,4.0,2.10,Excellent Mileage,Maruti,Alto
4017,4141,Maruti Wagon R CNG LXI,Mumbai,2014,47200,CNG,Manual,First,33.54,998.0,67.04,5.0,2.85,Excellent Mileage,Maruti,Wagon
4627,4769,Maruti Alto 800 2016-2019 CNG LXI,Kochi,2017,24310,CNG,Manual,First,33.44,796.0,40.30,4.0,3.70,Excellent Mileage,Maruti,Alto
5025,5178,Maruti Celerio CNG VXI MT,Delhi,2015,64687,CNG,Manual,First,31.79,998.0,58.33,5.0,3.80,Excellent Mileage,Maruti,Celerio
5546,5710,Maruti Alto 800 CNG LXI,Mumbai,2013,26200,CNG,Manual,First,30.46,796.0,47.30,5.0,2.15,Excellent Mileage,Maruti,Alto
5764,5935,Maruti Alto K10 LXI CNG,Pune,2015,59525,CNG,Manual,Second,32.26,998.0,58.20,4.0,3.10,Excellent Mileage,Maruti,Alto

In [42]:
# filter data with multiple condition  (and)
# select all the data where mileage >=30 and Transmission ='Manual' 
con1 = data['Mileage']>=30 
con2 = data['Transmission']=='Manual'

In [53]:
test = data[con1 & con2 ]
test.head(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
1228,1269,Maruti Alto 800 2016-2019 CNG LXI,Mumbai,2018,10600,CNG,Manual,First,33.44,796.0,40.30,4.0,3.50,Excellent Mileage,Maruti,Alto
1286,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04,5.0,2.96,Excellent Mileage,Maruti,Wagon

In [52]:
# filter data with multiple condition  (or)
#  select all data where mileage >=32 or fuel_type= 'LPG'

In [57]:
con1 = data['Mileage']>=32
con2 = data['Fuel_Type']=='LPG'

In [58]:
data[con1 | con2]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
5,5,Hyundai EON LPG Era Plus Option,Hyderabad,2012,75000,LPG,Manual,First,21.10,814.0,55.20,5.0,2.35,Good Mileage,Hyundai,EON
902,936,Maruti Wagon R LXI LPG BSIV,Hyderabad,2012,72000,LPG,Manual,First,26.20,998.0,58.20,5.0,2.85,Good Mileage,Maruti,Wagon
952,987,Maruti Wagon R LXI DUO BSIII,Mumbai,2008,64226,LPG,Manual,First,17.30,1061.0,57.50,5.0,1.45,Nice Mileage,Maruti,Wagon
1228,1269,Maruti Alto 800 2016-2019 CNG LXI,Mumbai,2018,10600,CNG,Manual,First,33.44,796.0,40.30,4.0,3.50,Excellent Mileage,Maruti,Alto
1286,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04,5.0,2.96,Excellent Mileage,Maruti,Wagon
1998,2059,Maruti Wagon R CNG LXI,Mumbai,2013,54000,CNG,Manual,First,33.54,998.0,67.04,5.0,3.05,Excellent Mileage,Maruti,Wagon
2210,2278,Hyundai Santro Xing GLS LPG,Pune,2010,55000,LPG,Manual,Second,13.45,1086.0,62.10,5.0,1.65,Nice Mileage,Hyundai,Santro
2298,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04,5.0,3.90,Excellent Mileage,Maruti,Wagon
2312,2385,Hyundai Santro Xing GLS LPG,Hyderabad,2011,17000,LPG,Manual,First,13.45,1086.0,62.10,5.0,3.10,Nice Mileage,Hyundai,Santro
2362,2436,Hyundai i10 Magna LPG,Jaipur,2012,53000,LPG,Manual,Second,19.20,1086.0,68.05,5.0,2.85,Nice Mileage,Hyundai,i10
2849,2941,Hyundai Santro Xing GL Plus LPG,Hyderabad,2014,56000,LPG,Manual,First,13.45,1086.0,62.10,5.0,3.20,Nice Mileage,Hyundai,Santro
3022,3119,Maruti Alto K10 LXI CNG Optional,Kochi,2018,44202,CNG,Manual,First,32.26,998.0,58.20,4.0,4.00,Excellent Mileage,Maruti,Alto
3032,3129,Maruti Wagon R CNG LXI,Delhi,2014,74663,CNG,Manual,First,33.54,998.0,67.04,5.0,3.25,Excellent Mileage,Maruti,Wagon
3444,3553,Maruti Alto 800 2016-2019 CNG LXI,Pune,2015,18000,CNG,Manual,First,33.44,796.0,40.30,4.0,3.00,Excellent Mileage,Maruti,Alto
3485,3595,Maruti Wagon R LX DUO BSIII,Hyderabad,2007,65047,LPG,Manual,First,17.30,1061.0,57.50,5.0,1.95,Nice Mileage,Maruti,Wagon
3752,3869,Maruti Alto 800 2016-2019 CNG LXI,Delhi,2012,65537,CNG,Manual,Second,33.44,796.0,40.30,4.0,2.10,Excellent Mileage,Maruti,Alto
4017,4141,Maruti Wagon R CNG LXI,Mumbai,2014,47200,CNG,Manual,First,33.54,998.0,67.04,5.0,2.85,Excellent Mileage,Maruti,Wagon
4627,4769,Maruti Alto 800 2016-2019 CNG LXI,Kochi,2017,24310,CNG,Manual,First,33.44,796.0,40.30,4.0,3.70,Excellent Mileage,Maruti,Alto
5345,5506,Maruti Wagon R Duo LX BSIII,Hyderabad,2012,72389,LPG,Manual,First,26.20,998.0,58.20,5.0,3.20,Good Mileage,Maruti,Wagon
5764,5935,Maruti Alto K10 LXI CNG,Pune,2015,59525,CNG,Manual,Second,32.26,998.0,58.20,4.0,3.10,Excellent Mileage,Maruti,Alto
5823,5997,Maruti Wagon R Duo Lxi,Jaipur,2010,70000,LPG,Manual,First,26.20,998.0,58.20,5.0,2.27,Good Mileage,Maruti,Wagon

In [60]:
# using not conditio 
# select all the values except Transmission is Manual 
data[data['Transmission']!='Manual']

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74,Nice Mileage,Audi,A4
7,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36,2755.0,171.50,8.0,17.50,Nice Mileage,Toyota,Innova
11,11,Honda City 1.5 V AT Sunroof,Kolkata,2012,60000,Petrol,Automatic,First,16.80,1497.0,116.30,5.0,4.49,Nice Mileage,Honda,City
13,13,Land Rover Range Rover 2.2L Pure,Delhi,2014,72000,Diesel,Automatic,First,12.70,2179.0,187.70,5.0,27.00,Nice Mileage,Land,Rover
18,19,Mercedes-Benz New C-Class C 220 CDI BE Avantgare,Bangalore,2014,78500,Diesel,Automatic,First,14.84,2143.0,167.62,5.0,28.00,Nice Mileage,Mercedes-Benz,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5822,5996,Jaguar XF 2.2 Litre Luxury,Kochi,2016,31150,Diesel,Automatic,First,16.36,2179.0,187.70,5.0,30.54,Nice Mileage,Jaguar,XF
5827,6001,Audi A6 2011-2015 2.0 TDI,Kochi,2013,91903,Diesel,Automatic,First,17.68,1968.0,174.33,5.0,17.56,Nice Mileage,Audi,A6
5832,6006,Mercedes-Benz M-Class ML 320 CDI,Mumbai,2009,102002,Diesel,Automatic,First,8.70,2987.0,224.34,5.0,10.75,Not Good Mileage,Mercedes-Benz,M-Class
5834,6008,Porsche Panamera Diesel,Hyderabad,2013,40000,Diesel,Automatic,Second,17.85,2967.0,300.00,4.0,45.00,Nice Mileage,Porsche,Panamera
5835,6009,Toyota Camry Hybrid,Mumbai,2015,33500,Petrol,Automatic,First,19.16,2494.0,158.20,5.0,19.75,Nice Mileage,Toyota,Camry

# Sorting Data

In [61]:
data

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,Good Mileage,Maruti,Wagon
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,Nice Mileage,Hyundai,Creta
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.50,Nice Mileage,Honda,Jazz
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00,Good Mileage,Maruti,Ertiga
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74,Nice Mileage,Audi,A4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5839,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.40,1248.0,74.00,5.0,4.75,Good Mileage,Maruti,Swift
5840,6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.40,1120.0,71.00,5.0,4.00,Good Mileage,Hyundai,Xcent
5841,6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.00,2498.0,112.00,8.0,2.90,Nice Mileage,Mahindra,Xylo
5842,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.90,998.0,67.10,5.0,2.65,Nice Mileage,Maruti,Wagon
5843,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936.0,57.60,5.0,2.50,Good Mileage,Chevrolet,Beat

In [63]:
# sort the data on basis of Mileage,  in ascending order 
data.sort_values(by='Mileage')

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
5615,5781,Lamborghini Gallardo Coupe,Delhi,2011,6500,Petrol,Automatic,Third,6.40,5204.0,560.00,2.0,120.00,Not Good Mileage,Lamborghini,Gallardo
5440,5603,Porsche Panamera 2010 2013 Diesel,Delhi,2013,36400,Diesel,Automatic,First,7.50,4806.0,394.30,4.0,72.00,Not Good Mileage,Porsche,Panamera
145,152,Mercedes-Benz S Class 2005 2013 S 500,Kolkata,2010,35277,Petrol,Automatic,First,7.81,5461.0,362.90,5.0,30.00,Not Good Mileage,Mercedes-Benz,S
4493,4627,BMW 6 Series 650i Coupe,Kochi,2010,65329,Petrol,Automatic,First,7.94,4395.0,450.00,4.0,20.72,Not Good Mileage,BMW,6
4679,4821,BMW 6 Series 630i Coupe,Mumbai,2011,5900,Petrol,Automatic,First,7.94,4395.0,450.00,4.0,47.50,Not Good Mileage,BMW,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4017,4141,Maruti Wagon R CNG LXI,Mumbai,2014,47200,CNG,Manual,First,33.54,998.0,67.04,5.0,2.85,Excellent Mileage,Maruti,Wagon
1998,2059,Maruti Wagon R CNG LXI,Mumbai,2013,54000,CNG,Manual,First,33.54,998.0,67.04,5.0,3.05,Excellent Mileage,Maruti,Wagon
3032,3129,Maruti Wagon R CNG LXI,Delhi,2014,74663,CNG,Manual,First,33.54,998.0,67.04,5.0,3.25,Excellent Mileage,Maruti,Wagon
2298,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04,5.0,3.90,Excellent Mileage,Maruti,Wagon
1286,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04,5.0,2.96,Excellent Mileage,Maruti,Wagon

In [64]:
# sort values in descnding order 
data.sort_values(by='Mileage', ascending = False)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
4017,4141,Maruti Wagon R CNG LXI,Mumbai,2014,47200,CNG,Manual,First,33.54,998.0,67.04,5.0,2.85,Excellent Mileage,Maruti,Wagon
3032,3129,Maruti Wagon R CNG LXI,Delhi,2014,74663,CNG,Manual,First,33.54,998.0,67.04,5.0,3.25,Excellent Mileage,Maruti,Wagon
1286,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04,5.0,2.96,Excellent Mileage,Maruti,Wagon
1998,2059,Maruti Wagon R CNG LXI,Mumbai,2013,54000,CNG,Manual,First,33.54,998.0,67.04,5.0,3.05,Excellent Mileage,Maruti,Wagon
2298,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04,5.0,3.90,Excellent Mileage,Maruti,Wagon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4679,4821,BMW 6 Series 630i Coupe,Mumbai,2011,5900,Petrol,Automatic,First,7.94,4395.0,450.00,4.0,47.50,Not Good Mileage,BMW,6
4493,4627,BMW 6 Series 650i Coupe,Kochi,2010,65329,Petrol,Automatic,First,7.94,4395.0,450.00,4.0,20.72,Not Good Mileage,BMW,6
145,152,Mercedes-Benz S Class 2005 2013 S 500,Kolkata,2010,35277,Petrol,Automatic,First,7.81,5461.0,362.90,5.0,30.00,Not Good Mileage,Mercedes-Benz,S
5440,5603,Porsche Panamera 2010 2013 Diesel,Delhi,2013,36400,Diesel,Automatic,First,7.50,4806.0,394.30,4.0,72.00,Not Good Mileage,Porsche,Panamera
5615,5781,Lamborghini Gallardo Coupe,Delhi,2011,6500,Petrol,Automatic,Third,6.40,5204.0,560.00,2.0,120.00,Not Good Mileage,Lamborghini,Gallardo

In [68]:
# Multi level Sorting 
# sort values by location and the by mileage 
data.sort_values(by=['Mileage', 'Location'])

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
5615,5781,Lamborghini Gallardo Coupe,Delhi,2011,6500,Petrol,Automatic,Third,6.40,5204.0,560.00,2.0,120.00,Not Good Mileage,Lamborghini,Gallardo
5440,5603,Porsche Panamera 2010 2013 Diesel,Delhi,2013,36400,Diesel,Automatic,First,7.50,4806.0,394.30,4.0,72.00,Not Good Mileage,Porsche,Panamera
145,152,Mercedes-Benz S Class 2005 2013 S 500,Kolkata,2010,35277,Petrol,Automatic,First,7.81,5461.0,362.90,5.0,30.00,Not Good Mileage,Mercedes-Benz,S
4493,4627,BMW 6 Series 650i Coupe,Kochi,2010,65329,Petrol,Automatic,First,7.94,4395.0,450.00,4.0,20.72,Not Good Mileage,BMW,6
4679,4821,BMW 6 Series 630i Coupe,Mumbai,2011,5900,Petrol,Automatic,First,7.94,4395.0,450.00,4.0,47.50,Not Good Mileage,BMW,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3032,3129,Maruti Wagon R CNG LXI,Delhi,2014,74663,CNG,Manual,First,33.54,998.0,67.04,5.0,3.25,Excellent Mileage,Maruti,Wagon
1998,2059,Maruti Wagon R CNG LXI,Mumbai,2013,54000,CNG,Manual,First,33.54,998.0,67.04,5.0,3.05,Excellent Mileage,Maruti,Wagon
4017,4141,Maruti Wagon R CNG LXI,Mumbai,2014,47200,CNG,Manual,First,33.54,998.0,67.04,5.0,2.85,Excellent Mileage,Maruti,Wagon
1286,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04,5.0,2.96,Excellent Mileage,Maruti,Wagon
2298,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04,5.0,3.90,Excellent Mileage,Maruti,Wagon

# Must Know Function in Pandas

In [69]:
# value_counts() # unique() , # nunique()  # sum() # max() # min() # std()

In [70]:
# value_counts() counts the frequency of each item in a column 
data.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,Good Mileage,Maruti,Wagon
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,Nice Mileage,Hyundai,Creta
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.50,Nice Mileage,Honda,Jazz
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00,Good Mileage,Maruti,Ertiga
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74,Nice Mileage,Audi,A4

In [71]:
data['Location'].value_counts()

Location
Mumbai        773
Hyderabad     713
Kochi         643
Coimbatore    626
Pune          590
Delhi         543
Kolkata       519
Chennai       475
Jaipur        401
Bangalore     343
Ahmedabad     218
Name: count, dtype: int64

In [73]:
# unique() retursn unique values in a column 
data['Transmission'].unique()

<StringArray>
['Manual', 'Automatic']
Length: 2, dtype: str

In [74]:
data['Location'].unique()

<StringArray>
[    'Mumbai',       'Pune',    'Chennai', 'Coimbatore',  'Hyderabad',
     'Jaipur',      'Kochi',    'Kolkata',      'Delhi',  'Bangalore',
  'Ahmedabad']
Length: 11, dtype: str

In [75]:
# nunique() count the number  of unique values 
data['Location'].nunique()

11

In [77]:
data['brand'].nunique()

30

In [78]:
data['brand'].unique()

<StringArray>
[       'Maruti',       'Hyundai',         'Honda',          'Audi',
        'Nissan',        'Toyota',    'Volkswagen',          'Tata',
          'Land',    'Mitsubishi',       'Renault', 'Mercedes-Benz',
           'BMW',      'Mahindra',          'Ford',       'Porsche',
        'Datsun',        'Jaguar',         'Volvo',     'Chevrolet',
         'Skoda',          'Mini',          'Fiat',          'Jeep',
    'Ambassador',         'Isuzu',         'ISUZU',         'Force',
       'Bentley',   'Lamborghini']
Length: 30, dtype: str

In [79]:
data['brand'].value_counts()

brand
Maruti           1175
Hyundai          1051
Honda             600
Toyota            394
Volkswagen        314
Mercedes-Benz     304
Ford              294
Mahindra          268
BMW               262
Audi              234
Tata              183
Skoda             170
Renault           145
Chevrolet         120
Nissan             89
Land               51
Jaguar             40
Mitsubishi         27
Mini               26
Fiat               23
Volvo              21
Porsche            16
Jeep               15
Datsun             13
Force               3
ISUZU               2
Ambassador          1
Isuzu               1
Bentley             1
Lamborghini         1
Name: count, dtype: int64

In [80]:
# max()
data['Mileage'].max()

np.float64(33.54)

In [81]:
# min()
data['Mileage'].min()

np.float64(6.4)

In [82]:
# mean() 
data['Mileage'].mean()

np.float64(18.36541238877481)

In [83]:
# std() standard deviation 
data['Mileage'].std()

np.float64(4.188280146799944)

In [84]:
# median() 
data['Mileage'].median()

np.float64(18.33)

In [85]:
# percentiles() 
data['Mileage'].quantile(0.25)

np.float64(15.3)

In [86]:
data['Mileage'].quantile(0.75)

np.float64(21.1)

In [90]:
# find top 5 most selling brand 
data['brand'].value_counts().head()

brand
Maruti        1175
Hyundai       1051
Honda          600
Toyota         394
Volkswagen     314
Name: count, dtype: int64

In [96]:
# get all data where mileage >=30 
con = data['Mileage']>=30

In [100]:
data[data['Mileage']>=30].head(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
1228,1269,Maruti Alto 800 2016-2019 CNG LXI,Mumbai,2018,10600,CNG,Manual,First,33.44,796.0,40.30,4.0,3.50,Excellent Mileage,Maruti,Alto
1286,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04,5.0,2.96,Excellent Mileage,Maruti,Wagon

In [101]:
data

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,Good Mileage,Maruti,Wagon
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,Nice Mileage,Hyundai,Creta
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.50,Nice Mileage,Honda,Jazz
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00,Good Mileage,Maruti,Ertiga
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74,Nice Mileage,Audi,A4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5839,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.40,1248.0,74.00,5.0,4.75,Good Mileage,Maruti,Swift
5840,6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.40,1120.0,71.00,5.0,4.00,Good Mileage,Hyundai,Xcent
5841,6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.00,2498.0,112.00,8.0,2.90,Nice Mileage,Mahindra,Xylo
5842,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.90,998.0,67.10,5.0,2.65,Nice Mileage,Maruti,Wagon
5843,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936.0,57.60,5.0,2.50,Good Mileage,Chevrolet,Beat

# Droping , Arranging and Renaming columns

In [102]:
# delete (droop) single  column

In [103]:
data.columns

Index(['S.No.', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'Price', 'mileage_type', 'brand', 'model'],
      dtype='str')

In [107]:
data.drop('S.No.', axis=1,inplace=True)

In [108]:
data.head(2)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type,brand,model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,Good Mileage,Maruti,Wagon
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,Nice Mileage,Hyundai,Creta

In [111]:
# Drop Multiple Columns 
# Drip 'brand', 'model' 
data.drop(['brand', 'model'], axis=1, inplace=True)

In [112]:
data.head(2)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,mileage_type
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,Good Mileage
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,Nice Mileage

# Renaming Columns

In [113]:
data.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'Price', 'mileage_type'],
      dtype='str')

In [114]:
data.rename(columns={'Kilometers_Driven':'run','Fuel_Type':'fuel','Transmission':'trans','Owner_Type':'owner'},inplace=True)

In [115]:
data.head(2)

,Name,Location,Year,run,fuel,trans,owner,Mileage,Engine,Power,Seats,Price,mileage_type
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,Good Mileage
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,Nice Mileage

In [116]:
# Columns Arrany 
data.columns

Index(['Name', 'Location', 'Year', 'run', 'fuel', 'trans', 'owner', 'Mileage',
       'Engine', 'Power', 'Seats', 'Price', 'mileage_type'],
      dtype='str')

In [117]:
cols =['Location','Name','Year','run', 'fuel', 'trans', 'owner', 'Mileage',
       'Engine', 'Power', 'Seats', 'Price', 'mileage_type']

In [118]:
data.columns = cols

In [119]:
data

,Location,Name,Year,run,fuel,trans,owner,Mileage,Engine,Power,Seats,Price,mileage_type
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,Good Mileage
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,Nice Mileage
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.50,Nice Mileage
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00,Good Mileage
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74,Nice Mileage
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5839,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.40,1248.0,74.00,5.0,4.75,Good Mileage
5840,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.40,1120.0,71.00,5.0,4.00,Good Mileage
5841,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.00,2498.0,112.00,8.0,2.90,Nice Mileage
5842,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.90,998.0,67.10,5.0,2.65,Nice Mileage
5843,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936.0,57.60,5.0,2.50,Good Mileage

In [123]:
data.drop('S.No.', axis=1,  inplace=True)

In [125]:
data.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'Price', 'mileage_type', 'brand', 'model'],
      dtype='str')

In [126]:
cols=['Name','brand', 'model','Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'Price', 'mileage_type']

In [128]:
data= data[cols]

In [129]:
# Save the file 
data.to_csv('data_saved.csv', index=False)

In [ ]:
# gemin