In [1]:
import pandas as pd
import numpy as np

In [2]:
# load data 
data = pd.read_csv(r"C:\Users\Lenovo\Desktop\mixed\New folder\used_cars_data_uncleaned.csv")

In [ ]:
# Data Cleaning and Data transformation 
Handling missing data (fillna, dropna).
Renaming columns.
Adding and Dropping Columns
Data Type Conversion
Replacing Values

In [ ]:
# Data cleanign is the process or removin unwanted data 
fill and remove null values , 
# Change the data accord to the requirement data transformation (add /remove col, changin data types)

In [3]:
# Preview the data 
data.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              7253 non-null   int64
 1   Name               7253 non-null   str
 2   Location           7253 non-null   str
 3   Year               7253 non-null   int64
 4   Kilometers_Driven  7253 non-null   int64
 5   Fuel_Type          7253 non-null   str
 6   Transmission       7253 non-null   str
 7   Owner_Type         7253 non-null   str
 8   Mileage            7251 non-null   str
 9   Engine             7207 non-null   str
 10  Power              7207 non-null   str
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   str
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), str(9)
memory usage: 793.4 KB

In [ ]:
mileage, power, enginer : nu

In [5]:
data.Mileage

0       26.6 km/kg
1       19.67 kmpl
2        18.2 kmpl
3       20.77 kmpl
4        15.2 kmpl
           ...
7248    20.54 kmpl
7249    17.21 kmpl
7250    23.08 kmpl
7251     17.2 kmpl
7252     10.0 kmpl
Name: Mileage, Length: 7253, dtype: str

In [6]:
# check null values  # isna() isused to find null values in a dataset 

data.isna().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

# Handeing Null or Missing Values

In [7]:
# Drop or Fill

In [8]:
# drop , .dropna() is used to drop null values

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
7,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36 kmpl,2755 CC,171.5 bhp,8.0,21 Lakh,17.50
10,10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol,Manual,First,21.56 kmpl,1462 CC,103.25 bhp,5.0,10.65 Lakh,9.95
15,15,Mitsubishi Pajero Sport 4X4,Delhi,2014,110000,Diesel,Manual,First,13.5 kmpl,2477 CC,175.56 bhp,7.0,32.01 Lakh,15.00
20,20,BMW 3 Series 320d,Kochi,2014,32982,Diesel,Automatic,First,22.69 kmpl,1995 CC,190 bhp,5.0,47.87 Lakh,18.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5999,5999,Tata Bolt Revotron XT,Chennai,2016,10000,Petrol,Manual,First,17.57 kmpl,1193 CC,88.7 bhp,5.0,7.77 Lakh,4.00
6002,6002,Volkswagen Vento 1.6 Highline,Mumbai,2011,38000,Petrol,Manual,First,16.09 kmpl,1598 CC,103.5 bhp,5.0,11.91 Lakh,3.25
6005,6005,Maruti Vitara Brezza VDi,Pune,2016,37208,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,9.93 Lakh,7.43
6010,6010,Honda Brio 1.2 VX MT,Delhi,2013,33746,Petrol,Manual,First,18.5 kmpl,1198 CC,86.8 bhp,5.0,6.63 Lakh,3.20
6014,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75

In [10]:
data.isna().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

In [12]:
# drop columns New_Price and Price , since they have huge amount of null values 
data.drop(['New_Price', 'Price'], axis=1,inplace=True)

In [13]:
data.head(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0

In [14]:
data.drop('S.No.', axis=1,inplace=True)
data.head(2)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0

In [18]:
# splitting columns 
data['Mileage'] = data.Mileage.str.split(' ',expand=True)[0]
data.head(2)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6,998 CC,58.16 bhp,5.0
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582 CC,126.2 bhp,5.0

In [21]:
# Replacing Values 
data['Engine'] = data['Engine'].str.replace('CC', ' ')

In [22]:
data.head(2)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6,998,58.16 bhp,5.0
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.2 bhp,5.0

In [24]:
# Replace 'bhp' with ' ' in Power Column 
data['Power'] = data['Power'].str.replace('bhp', ' ')

In [25]:
data.head(2)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6,998,58.16,5.0
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.2,5.0

In [26]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               7253 non-null   str
 1   Location           7253 non-null   str
 2   Year               7253 non-null   int64
 3   Kilometers_Driven  7253 non-null   int64
 4   Fuel_Type          7253 non-null   str
 5   Transmission       7253 non-null   str
 6   Owner_Type         7253 non-null   str
 7   Mileage            7251 non-null   str
 8   Engine             7207 non-null   str
 9   Power              7207 non-null   str
 10  Seats              7200 non-null   float64
dtypes: float64(1), int64(2), str(8)
memory usage: 623.4 KB

In [30]:
# Since, data type of Mileage, Engine and Power is still 'str' we have to chage data type 
data['Power'] = pd.to_numeric(data['Power'], errors='coerce')

In [32]:
data['Engine'] = pd.to_numeric(data['Engine'], errors='coerce')

In [35]:
data['Mileage'] = pd.to_numeric(data['Mileage'], errors='coerce')

In [36]:
# check the data type 
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               7253 non-null   str
 1   Location           7253 non-null   str
 2   Year               7253 non-null   int64
 3   Kilometers_Driven  7253 non-null   int64
 4   Fuel_Type          7253 non-null   str
 5   Transmission       7253 non-null   str
 6   Owner_Type         7253 non-null   str
 7   Mileage            7251 non-null   float64
 8   Engine             7207 non-null   float64
 9   Power              7078 non-null   float64
 10  Seats              7200 non-null   float64
dtypes: float64(4), int64(2), str(5)
memory usage: 623.4 KB

In [37]:
# Find and Remove the null and missing values from mileage, engine and power

In [38]:
data[['Mileage', 'Engine','Power']].isna().sum()

Mileage      2
Engine      46
Power      175
dtype: int64

In [69]:
data['Mileage'] = data['Mileage'].dropna() # removes all rows where, mileage is null

In [71]:
data['Mileage'].isna().sum()

np.int64(2)

In [72]:
data.shape

(7253, 11)

In [73]:
# fill null values in engine with mean 
data[data['Engine'].isna()]

Empty DataFrame
Columns: [Name, Location, Year, Kilometers_Driven, Fuel_Type, Transmission, Owner_Type, Mileage, Engine, Power, Seats]
Index: []

In [53]:
# replace all NaN values in engine with mean enginge values 
data['Engine'].agg(['min', 'max', 'mean'])

min       72.00000
max     5998.00000
mean    1616.57347
Name: Engine, dtype: float64

In [54]:
mv= data['Engine'].mean()
mv

np.float64(1616.5734702372692)

In [56]:
# .fillna() is used to fill null values with given given values 
# sytax .fillna(value) 
data['Engine']=data['Engine'].fillna(mv)

In [57]:
data.Engine.isna().sum()

np.int64(0)

In [59]:
data[['Mileage','Engine','Power']].isna().sum()

Mileage      2
Engine       0
Power      175
dtype: int64

In [60]:
# fill na values for Power
data.Power.agg(['min', 'max','mean', 'median'])

min        34.200000
max       616.000000
mean      112.765214
median     94.000000
Name: Power, dtype: float64

In [61]:
# use, 'mean' of power to fill na 
mv_power  = data['Power'].mean()
mv_power

np.float64(112.76521404351512)

In [65]:
data['Power'] = data['Power'].fillna(mv_power)

In [66]:
data['Power'].isna().sum()

np.int64(0)

In [78]:
data[['Mileage', 'Power', 'Engine']].isna().sum()

Mileage    2
Power      0
Engine     0
dtype: int64

In [77]:
data['Mileage'] = data.Mileage.dropna()

In [79]:
data.isna().sum()

Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               2
Engine                0
Power                 0
Seats                53
dtype: int64

In [81]:
data['Seats'] = data['Seats'].fillna(5)

In [82]:
data

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0
...,...,...,...,...,...,...,...,...,...,...,...
7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54,1598.0,103.60,5.0
7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21,1197.0,103.60,5.0
7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08,1461.0,63.10,5.0
7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.20,1197.0,103.60,5.0
7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.00,2148.0,170.00,5.0

In [83]:
data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0

In [84]:
# From the column 'Name' get Brand and Model 
# First Word :- Brannd 
# Second Word Model

In [89]:
data['Name'].str.split(' ',expand=True)[0]

0              Maruti
1             Hyundai
2               Honda
3              Maruti
4                Audi
            ...
7248       Volkswagen
7249       Volkswagen
7250           Nissan
7251       Volkswagen
7252    Mercedes-Benz
Name: 0, Length: 7253, dtype: str

In [90]:
data['Brand'] = data['Name'].str.split(' ',expand=True)[0]
data.head(2)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Maruti
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,Hyundai

In [91]:
data['Model'] = data['Brand'] = data['Name'].str.split(' ',expand=True)[1]
data.head(2)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Wagon,Wagon
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,Creta,Creta

In [92]:
# Now, drop 'Name'
data.drop('Name', axis=1, inplace=True)
data.head(2)

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Wagon,Wagon
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,Creta,Creta

In [93]:
# Replacinng Values 
data['Mileage'].min()

np.float64(0.0)

In [94]:
data['Mileage'].agg(['min', 'max', 'mean'])

min      0.00000
max     33.54000
mean    18.14158
Name: Mileage, dtype: float64

In [95]:
data[data['Mileage']==0.0]

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model
14,Pune,2012,85000,Diesel,Automatic,Second,0.0,2179.00000,115.000000,5.0,Rover,Rover
67,Coimbatore,2019,15369,Diesel,Automatic,First,0.0,1950.00000,194.000000,5.0,C-Class,C-Class
79,Hyderabad,2005,87591,Petrol,Manual,First,0.0,1086.00000,112.765214,5.0,Santro,Santro
194,Ahmedabad,2007,60006,Petrol,Manual,First,0.0,1616.57347,112.765214,5.0,City,City
229,Bangalore,2015,70436,Diesel,Manual,First,0.0,1498.00000,99.000000,5.0,Figo,Figo
...,...,...,...,...,...,...,...,...,...,...,...,...
6633,Kolkata,2016,27000,Diesel,Manual,First,0.0,1616.57347,112.765214,5.0,TUV,TUV
6697,Jaipur,2007,85000,Petrol,Manual,Second,0.0,1086.00000,112.765214,5.0,Santro,Santro
6857,Mumbai,2011,87000,Diesel,Automatic,First,0.0,2179.00000,115.000000,5.0,Rover,Rover
6957,Kochi,2019,11574,Petrol,Manual,First,0.0,1199.00000,88.700000,5.0,Jazz,Jazz
7226,Ahmedabad,2014,41000,Petrol,Manual,First,0.0,1086.00000,62.000000,5.0,Santro,Santro

In [96]:
data.sort_values(by='Mileage')

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model
7226,Ahmedabad,2014,41000,Petrol,Manual,First,0.00,1086.0,62.000000,5.0,Santro,Santro
5647,Mumbai,2001,227000,Diesel,Manual,Fourth & Above,0.00,2446.0,112.765214,8.0,Qualis,Qualis
707,Pune,2014,120000,Diesel,Automatic,First,0.00,2987.0,165.000000,5.0,M-Class,M-Class
6697,Jaipur,2007,85000,Petrol,Manual,Second,0.00,1086.0,112.765214,5.0,Santro,Santro
6093,Bangalore,2007,47000,Petrol,Manual,Second,0.00,1086.0,112.765214,5.0,Santro,Santro
...,...,...,...,...,...,...,...,...,...,...,...,...
2059,Mumbai,2013,54000,CNG,Manual,First,33.54,998.0,67.040000,5.0,Wagon,Wagon
2371,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.040000,5.0,Wagon,Wagon
1332,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.040000,5.0,Wagon,Wagon
4446,Chennai,2016,50000,Electric,Automatic,First,NaN,72.0,41.000000,5.0,E,E
4904,Mumbai,2011,44000,Electric,Automatic,First,NaN,1798.0,73.000000,5.0,Prius,Prius

In [100]:
data['Mileage'].value_counts().sort_index()

Mileage
0.00     81
6.40      1
7.50      1
7.81      1
7.94      3
         ..
30.46     2
31.79     2
32.26     5
33.44     4
33.54     5
Name: count, Length: 438, dtype: int64

In [102]:
# replace all 0.0 in Mileage by 6.4 
data['Mileage']  = data['Mileage'].replace(0.0, 6.4)

In [103]:
data['Mileage'].min()

np.float64(6.4)

In [104]:
data.isna().sum()

Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              2
Engine               0
Power                0
Seats                0
Brand                0
Model                0
dtype: int64

In [108]:
data[data['Mileage'].isna()]

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model
4446,Chennai,2016,50000,Electric,Automatic,First,NaN,72.0,41.0,5.0,E,E
4904,Mumbai,2011,44000,Electric,Automatic,First,NaN,1798.0,73.0,5.0,Prius,Prius

In [107]:
data['Mileage'] = data['Mileage'].dropna()

In [109]:
data[data['Mileage'].isna()]

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model
4446,Chennai,2016,50000,Electric,Automatic,First,NaN,72.0,41.0,5.0,E,E
4904,Mumbai,2011,44000,Electric,Automatic,First,NaN,1798.0,73.0,5.0,Prius,Prius

In [110]:
data.head(2)

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Wagon,Wagon
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,Creta,Creta

# Renaming Columns

In [111]:
# rename the columns 'Kilomers... en' to 'run'
# .rename() is used to rename columns 
data.rename(columns={'Kilometers_Driven':'run'},inplace=True)

In [112]:
data.head()

,Location,Year,run,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Wagon,Wagon
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,Creta,Creta
2,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,Jazz,Jazz
3,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,Ertiga,Ertiga
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,A4,A4

In [113]:
# rename 'fuel_type' : - fuel , 'owner_type' :- owner
data.rename(columns={'Fuel_Type':'fuel','Owner_Type':'owner'}, inplace=True)

In [114]:
data.head(2)

,Location,Year,run,fuel,Transmission,owner,Mileage,Engine,Power,Seats,Brand,Model
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Wagon,Wagon
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,Creta,Creta

# Adding Columns

In [116]:
data['Engine'].agg(['min', 'max', 'median'])

min         72.0
max       5998.0
median    1493.0
Name: Engine, dtype: float64

In [ ]:
#  Add a conditonal colum, engine__type 
# >=2000,"Very Powerful", >=1000,"Powerful", '>=500' Moderate, 'lesspowerful

In [117]:
# Create a function 
def classify(value): 
    if value>=2000: 
        return  "Very Powerful"
    elif value >=1000: 
        return "Powerful"
    elif value >=500:
        return "Moderate" 
    else: 
        return "Less Powerful"

In [119]:
data['Engine Type'] = data['Engine'].apply(classify)

In [120]:
data.head(2)

,Location,Year,run,fuel,Transmission,owner,Mileage,Engine,Power,Seats,Brand,Model,Engine Type
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Wagon,Wagon,Moderate
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,Creta,Creta,Powerful

In [122]:
# Calcuative Columns 
# Get 10 % of Power Values  
data['Power 10P']= data['Power']*0.1

In [123]:
data

,Location,Year,run,fuel,Transmission,owner,Mileage,Engine,Power,Seats,Brand,Model,Engine Type,Power 10P
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Wagon,Wagon,Moderate,5.816
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,Creta,Creta,Powerful,12.620
2,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,Jazz,Jazz,Powerful,8.870
3,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,Ertiga,Ertiga,Powerful,8.876
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,A4,A4,Powerful,14.080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,Hyderabad,2011,89411,Diesel,Manual,First,20.54,1598.0,103.60,5.0,Vento,Vento,Powerful,10.360
7249,Mumbai,2015,59000,Petrol,Automatic,First,17.21,1197.0,103.60,5.0,Polo,Polo,Powerful,10.360
7250,Kolkata,2012,28000,Diesel,Manual,First,23.08,1461.0,63.10,5.0,Micra,Micra,Powerful,6.310
7251,Pune,2013,52262,Petrol,Automatic,Third,17.20,1197.0,103.60,5.0,Polo,Polo,Powerful,10.360
7252,Kochi,2014,72443,Diesel,Automatic,First,10.00,2148.0,170.00,5.0,E-Class,E-Class,Very Powerful,17.000

In [ ]:
# GroupBy operations
# Aggregation (sum, mean, count)

In [124]:
# Aggerations function are use to find summary

In [127]:
data['Mileage'].sum() # find the sum of all values in column 'Mileage'

np.float64(132063.0)

In [128]:
# max() 
data['Mileage'].max()

np.float64(33.54)

In [129]:
#  min() 
data['Mileage'].min()

np.float64(6.4)

In [130]:
# mean() 
data['Mileage'].mean()

np.float64(18.213074058750518)

In [131]:
#  median() 
data['Mileage'].median()

np.float64(18.16)

In [132]:
# std() standard deviation 
data['Mileage'].std()

np.float64(4.321085134773767)

In [134]:
#agg() 
data['Mileage'].agg(['min', 'max','mean', 'std'])

min      6.400000
max     33.540000
mean    18.213074
std      4.321085
Name: Mileage, dtype: float64

In [136]:
data['Mileage'].var()

np.float64(18.671776741962823)

# Group By

In [137]:
# Grouping the values and finding summary 
# find the max  mileage of each location 
data['Mileage'].max()

np.float64(33.54)

In [138]:
data['Location'].nunique()

11

In [139]:
# groupby() 
data.groupby('Location')['Mileage'].max()

Location
Ahmedabad     28.40
Bangalore     28.09
Chennai       28.40
Coimbatore    28.40
Delhi         33.54
Hyderabad     28.40
Jaipur        28.40
Kochi         33.44
Kolkata       30.46
Mumbai        33.54
Pune          33.54
Name: Mileage, dtype: float64

In [142]:
# Find the min mileage value of each model
data.groupby('Brand')['Mileage'].min()

Brand
1          20.58
1.4Gsi     14.20
1000       15.00
3           8.20
370Z       10.00
           ...
Zen        17.30
Zest       17.57
i10        16.00
i20        15.00
redi-GO    22.70
Name: Mileage, Length: 219, dtype: float64

In [146]:
# Multiple Grouping 
# For Each Location , find the minimum Mileage according to 'Transmission'
data.groupby(['Location','Transmission'])['Mileage'].mean()

Location    Transmission
Ahmedabad   Automatic       16.421389
            Manual          19.769655
Bangalore   Automatic       15.381508
            Manual          17.995287
Chennai     Automatic       16.268000
            Manual          18.651495
Coimbatore  Automatic       16.411122
            Manual          18.968081
Delhi       Automatic       14.941814
            Manual          19.277039
Hyderabad   Automatic       15.931034
            Manual          19.445575
Jaipur      Automatic       16.566935
            Manual          19.425995
Kochi       Automatic       16.043469
            Manual          19.898330
Kolkata     Automatic       15.372045
            Manual          19.833604
Mumbai      Automatic       15.623268
            Manual          18.388085
Pune        Automatic       15.868462
            Manual          18.746527
Name: Mileage, dtype: float64

In [154]:
# Groupby with multiple aggrationg 
# find max vallue of mileage, engine , power according to locoation 
df = data.groupby('Location')[['Mileage', 'Engine','Power']].agg(['min' , 'max', 'mean'])
df

           Mileage                   Engine                       Power  \
               min    max       mean    min     max         mean    min
Location
Ahmedabad      6.4  28.40  18.893018  624.0  2993.0  1582.587540  37.48
Bangalore      6.4  28.09  16.931955  624.0  5998.0  1811.067245  34.20
Chennai        6.4  28.40  18.106119   72.0  3200.0  1613.017169  35.50
Coimbatore     6.4  28.40  17.964508  624.0  5000.0  1694.899154  34.20
Delhi          6.4  33.54  17.937061  624.0  5204.0  1709.210405  37.48
Hyderabad      6.4  28.40  18.514783  624.0  5998.0  1643.538326  34.20
Jaipur         6.4  28.40  19.070762  624.0  3198.0  1441.207857  34.20
Kochi          6.4  33.44  18.674961  624.0  4951.0  1584.374733  34.20
Kolkata        6.4  30.46  19.233272  793.0  5461.0  1470.257555  34.20
Mumbai         6.4  33.54  17.343987  796.0  4806.0  1662.420752  34.20
Pune           6.4  33.54  18.110719  624.0  3498.0  1544.923836  34.20


               max        mean
Location
Ahmedabad   308.43  110.509167
Bangalore   616.00  132.124883
Chennai     308.43  106.946378
Coimbatore  503.00  123.515184
Delhi       560.00  120.215140
Hyderabad   552.00  110.231616
Jaipur      265.00   93.563202
Kochi       450.00  114.893091
Kolkata     387.30  101.045565
Mumbai      550.00  120.390888
Pune        321.00  103.499283

In [155]:
# Export 'df' to csv file 
df.to_csv('Location_performance.csv', index=False)

# 
Pivot Tables
Multi-Indexing
Merge, Join, and Concatenate

In [ ]:
Pivot Tables : - 
They are summary tables , more interactive 
Multi- Indexing
One-colummn , M

In [ ]:
1...... 3cr
Proive, dis

In [ ]:
# while working with two or more dif tables 
# merge , join, concate 
# SQL