In [1]:
import pandas as pd

In [3]:
# Create Two DAta Frames
list_x = list(range(9,91,9))
list_x

[9, 18, 27, 36, 45, 54, 63, 72, 81, 90]

In [5]:
list_y = list(range(13,131,13))
list_y

[13, 26, 39, 52, 65, 78, 91, 104, 117, 130]

In [17]:
df_1 = pd.DataFrame({'Mul_9':list_x, 'Mul_13' :list_y})
df_1

   Mul_9  Mul_13
0      9      13
1     18      26
2     27      39
3     36      52
4     45      65
5     54      78
6     63      91
7     72     104
8     81     117
9     90     130

In [34]:
df_1['index'] = range(len(df_1))
df_1

   Mul_9  Mul_13  index
0      9      13      0
1     18      26      1
2     27      39      2
3     36      52      3
4     45      65      4
5     54      78      5
6     63      91      6
7     72     104      7
8     81     117      8
9     90     130      9

In [35]:
#using Same concept
df2 = pd.DataFrame({'Mul_17':list(range(17,171,17)),'Mul_8' : list(range(8,81,8))})
df2

   Mul_17  Mul_8
0      17      8
1      34     16
2      51     24
3      68     32
4      85     40
5     102     48
6     119     56
7     136     64
8     153     72
9     170     80

In [36]:
#Concate, Merge

In [37]:
# Vertical Koin number of columns in both dataset must be equal.
# Horizontal Join at least one column must be sames

In [38]:
# Add Index Column in df_2
df2['index'] = range(len(df2))
df2

   Mul_17  Mul_8  index
0      17      8      0
1      34     16      1
2      51     24      2
3      68     32      3
4      85     40      4
5     102     48      5
6     119     56      6
7     136     64      7
8     153     72      8
9     170     80      9

In [39]:
# Merge
pd.merge(df_1,df2,on='index')

   Mul_9  Mul_13  index  Mul_17  Mul_8
0      9      13      0      17      8
1     18      26      1      34     16
2     27      39      2      51     24
3     36      52      3      68     32
4     45      65      4      85     40
5     54      78      5     102     48
6     63      91      6     119     56
7     72     104      7     136     64
8     81     117      8     153     72
9     90     130      9     170     80

In [23]:
df2.head(2)

   Mul_17  Mul_8  index
0      17      8      0
1      34     16      1

In [24]:
df_1.head(2)

   Mul_9  Mul_13
0      9      13
1     18      26