In [1]:
!pip install pandas

Requirement already satisfied: pandas in d:\python_class1\venv\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in d:\python_class1\venv\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\python_class1\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\python_class1\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in d:\python_class1\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Question with answers [Pandas]

## Q.1) Create a Pandas Series containing even numbers from 10 to 50(inclusive).What is the index of the value 30?

Inclusive meaning including both the starting and ending values.

In [5]:
import pandas as pd

In [6]:
# Create even numbers form 10 to 50
numbers = list(range(10,51,2))
# Create series
s = pd.Series(numbers)

print(s)

0     10
1     12
2     14
3     16
4     18
5     20
6     22
7     24
8     26
9     28
10    30
11    32
12    34
13    36
14    38
15    40
16    42
17    44
18    46
19    48
20    50
dtype: int64

## Q2. Create a Series using range(1, 20, 2) and display only the values at index positions 2, 4, and 6.

In [9]:
import pandas as pd

s = pd.Series(range(1,20,2))
print(s[[2,4,6]])

2     5
4     9
6    13
dtype: int64

## Q3. Create a DataFrame from the list [10, 20, 30, 40, 50] and rename its default column to "values".

In [12]:
import pandas as pd

data = [10,20,30,40,50]
df = pd.DataFrame(data) #pd.DataFrame(data) → creates a table (DataFrame)
print(df)

    0
0  10
1  20
2  30
3  40
4  50

In [13]:
df.columns = ["values"] #Default column name is 0
print(df) #df.columns = ["values"] → changes column name

   values
0      10
1      20
2      30
3      40
4      50

## Q4. Create a DataFrame from a dictionary with columns "Name", "Age", and "City" for at least 5 people. Display it.

Keys = column names → "Name", "Age", "City"
Values = list of data (at least 5 people)

In [17]:
import pandas as pd

data = {
    "Name" : ["Ming","Nisha","Rushab","Prajwal","Prasna"],
    "Age": [20,22,19,21,23],
    "City":["Kathmandu","Pokhara","Dharan","Biratnagar","Lalitpur"]
}
df = pd.DataFrame(data)  #converts it into a table
print(df)

      Name  Age        City
0     Ming   20   Kathmandu
1    Nisha   22     Pokhara
2   Rushab   19      Dharan
3  Prajwal   21  Biratnagar
4   Prasna   23    Lalitpur

## Q5. What is the key difference between a Pandas Series and a DataFrame? Give one code example for each.

| Feature   | Series                      | DataFrame                    |
| --------- | --------------------------- | ---------------------------- |
| Structure | 1-dimensional (like a list) | 2-dimensional (like a table) |
| Data      | Single column               | Multiple columns             |
| Example   | One list of values          | Table with rows & columns    |

In [18]:
# Example of pandas Series
import pandas as pd
s = pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [19]:
# Example of pandas Dataframe
import pandas as pd
df = pd.DataFrame({
    "Name":["Ming","Fursang"],
    "Age":[20,22]
})

print(df)

      Name  Age
0     Ming   20
1  Fursang   22

## Q6. Create a Series from a dictionary {"a": 100, "b": 200, "c": 300} and access the value for key "b".

In [20]:
import pandas as pd
data = {"a": 100,"b": 200,"c":300}
s = pd.Series(data)
print(s)

a    100
b    200
c    300
dtype: int64

In [21]:
print(s["b"])

200

## Q7. Create a DataFrame with 3 columns and 4 rows using a nested list. Assign custom column names.

In [22]:
import pandas as pd
data = [
    [1,"Mingma",20],
    [2,"Fursang",22],
    [3,"Rushab",19],
    [4,"Yakso",21],
]

df = pd.DataFrame(data, columns=["ID","Name","Age"])
print(df)

   ID     Name  Age
0   1   Mingma   20
1   2  Fursang   22
2   3   Rushab   19
3   4    Yakso   21

## Q8. Given a Series pd.Series([5, 10, 15, 20, 25]), multiply every value by 3 without using a loop.

In [23]:
import pandas as pd
s = pd.Series([5,10,15,20,25])
result = s * 3
print(result)

0    15
1    30
2    45
3    60
4    75
dtype: int64

## Section 2: Loading Data

In [34]:
import pandas as pd

df = pd.read_csv(r'C:\Users\mingm\Videos\data.csv')

In [46]:
df.head(3)

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brand,Model
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998,58.16,5,1.75,Maruti,Wagon
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.20,5,12.50,Hyundai,Creta
2,Chennai,2011,46000,Petrol,Manual,First,18.20,1199,88.70,5,4.50,Honda,Jazz

In [48]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [52]:
data_excel = pd.read_excel(r"C:\Users\mingm\Videos\data1.xlsx")
data_excel.head()

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brand,Model
0,Dubai,2010,72000,CNG,Manual,First,26.60,998,58.16,5,1.75,Maruti,Wagon
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.20,5,12.50,Hyundai,Creta
2,Chennai,2011,46000,Petrol,Manual,First,18.20,1199,88.70,5,4.50,Honda,Jazz
3,Chennai,2012,87000,Diesel,Manual,First,20.77,1248,88.76,7,6.00,Maruti,Ertiga
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968,140.80,5,17.74,Audi,A4

In [53]:
df.shape

(5844, 13)

| Feature      | `read_csv()`    | `read_excel()`              |
| ------------ | --------------- | --------------------------- |
| File type    | CSV             | Excel (.xlsx, .xls)         |
| Speed        | Faster          | Slightly slower             |
| Dependencies | No extra needed | Needs openpyxl/xlrd         |
| Structure    | Plain text      | Supports sheets, formatting |

## Section 3: Previewing Data

## Q14. You have a DataFrame df. Write code to display the last 7 rows.

In [54]:
df.tail(7)

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brand,Model
5837,Coimbatore,2011,45004,Diesel,Manual,First,12.80,2494,102.0,7,9.48,Toyota,Innova
5838,Coimbatore,2015,70602,Diesel,Manual,First,25.80,1498,98.6,5,4.83,Honda,Amaze
5839,Delhi,2014,27365,Diesel,Manual,First,28.40,1248,74.0,5,4.75,Maruti,Swift
5840,Jaipur,2015,100000,Diesel,Manual,First,24.40,1120,71.0,5,4.00,Hyundai,Xcent
5841,Jaipur,2012,55000,Diesel,Manual,Second,14.00,2498,112.0,8,2.90,Mahindra,Xylo
5842,Kolkata,2013,46000,Petrol,Manual,First,18.90,998,67.1,5,2.65,Maruti,Wagon
5843,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936,57.6,5,2.50,Chevrolet,Beat

## Q15. Write code using info() on a DataFrame and explain what 3 pieces of information it provides.

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5844 entries, 0 to 5843
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Location           5844 non-null   str
 1   Year               5844 non-null   int64
 2   Kilometers_Driven  5844 non-null   int64
 3   Fuel_Type          5844 non-null   str
 4   Transmission       5844 non-null   str
 5   Owner_Type         5844 non-null   str
 6   Mileage            5844 non-null   float64
 7   Engine             5844 non-null   int64
 8   Power              5844 non-null   float64
 9   Seats              5844 non-null   int64
 10  Price              5844 non-null   float64
 11  Brand              5844 non-null   str
 12  Model              5844 non-null   str
dtypes: float64(3), int64(4), str(6)
memory usage: 593.7 KB

## Q16. What does describe() return? Which columns does it include by default and why?

By default, it gives the following statistics for each column:

count → Number of non-null values
mean → Average of values
std → Standard deviation
min → Minimum value
25% → First quartile (25th percentile)
50% → Median (50th percentile)
75% → Third quartile (75th percentile)
max → Maximum value

Columns included by default:
Only numeric columns (int, float) are included by default
Reason: These statistics (mean, std, quartiles) are meaningful only for numeric data.

## Q17. Given df.shape returns (1500, 12), what does this tell you about the dataset?

In [56]:
(1500, 12)

(1500, 12)

This tells us the following about the dataset:

Number of rows: 1500 → There are 1500 records/observations in the dataset.
Number of columns: 12 → There are 12 features/attributes for each record.

## Q18. Write code to display all column names of a DataFrame df as a list.

In [57]:
list(df.columns)

['Location',
 'Year',
 'Kilometers_Driven',
 'Fuel_Type',
 'Transmission',
 'Owner_Type',
 'Mileage',
 'Engine',
 'Power',
 'Seats',
 'Price',
 'Brand',
 'Model']

## Q19. How would you display the first 10 rows and last 10 rows of a DataFrame in two separate outputs?

In [58]:
# First 10 rows
df.head(10)

# Last 10 rows
df.tail(10)

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brand,Model
5834,Hyderabad,2013,40000,Diesel,Automatic,Second,17.85,2967,300.0,4,45.00,Porsche,Panamera
5835,Mumbai,2015,33500,Petrol,Automatic,First,19.16,2494,158.2,5,19.75,Toyota,Camry
5836,Delhi,2013,33746,Petrol,Manual,First,18.50,1198,86.8,5,3.20,Honda,Brio
5837,Coimbatore,2011,45004,Diesel,Manual,First,12.80,2494,102.0,7,9.48,Toyota,Innova
5838,Coimbatore,2015,70602,Diesel,Manual,First,25.80,1498,98.6,5,4.83,Honda,Amaze
5839,Delhi,2014,27365,Diesel,Manual,First,28.40,1248,74.0,5,4.75,Maruti,Swift
5840,Jaipur,2015,100000,Diesel,Manual,First,24.40,1120,71.0,5,4.00,Hyundai,Xcent
5841,Jaipur,2012,55000,Diesel,Manual,Second,14.00,2498,112.0,8,2.90,Mahindra,Xylo
5842,Kolkata,2013,46000,Petrol,Manual,First,18.90,998,67.1,5,2.65,Maruti,Wagon
5843,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936,57.6,5,2.50,Chevrolet,Beat

## Q20. A DataFrame has columns with mixed data types. How does info() help you identify which columns have missing values?

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5844 entries, 0 to 5843
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Location           5844 non-null   str
 1   Year               5844 non-null   int64
 2   Kilometers_Driven  5844 non-null   int64
 3   Fuel_Type          5844 non-null   str
 4   Transmission       5844 non-null   str
 5   Owner_Type         5844 non-null   str
 6   Mileage            5844 non-null   float64
 7   Engine             5844 non-null   int64
 8   Power              5844 non-null   float64
 9   Seats              5844 non-null   int64
 10  Price              5844 non-null   float64
 11  Brand              5844 non-null   str
 12  Model              5844 non-null   str
dtypes: float64(3), int64(4), str(6)
memory usage: 593.7 KB

How it shows missing values:
Non-Null Count:
For each column, it shows the number of non-null values.
If this count is less than the total number of rows, that column has missing values.
Column Data Type:
You can see which type each column is (object, int64, float64, etc.), which helps decide how to handle missing data.
Quick Overview:
You can immediately spot which columns have missing entries without manually checking each one.

## Section 4: Indexing & Selection

## Q21. Select only the "Price" column from a DataFrame df using two different syntaxes.

df['Price']
df[['Price']]

## Q22. Select the columns "Name", "Year", and "Price" from df in a single line of code.

df[['Name', 'Year', 'Price']]

## Q23. Using loc[], select rows 5 through 15 (inclusive) and only the "Mileage" column.

df.loc[5:15, 'Mileage']

## Q24. Using loc[], select all rows but only the columns "Fuel_Type" and "Transmission".

df.loc[:, ['Fuel_Type', 'Transmission']]

## Q25. Using iloc[], select rows at index positions 20 to 40 and the first 4 columns.

df.iloc[20:41, 0:4]

## Q26. Using iloc[], select every 5th row between index 0 and 100, for all columns.

df.iloc[0:101:5, :]

## Q27. Select 25 random rows from a DataFrame df using the appropriate Pandas function.

df.sample(n=25)  #sample() → used for random sampling

## Q28. What is the difference between loc[] and iloc[]? Give a scenario where using iloc[] is more appropriate than loc[].

| Feature        | `loc[]`                         | `iloc[]`                            |
| -------------- | ------------------------------- | ----------------------------------- |
| Type           | **Label-based indexing**        | **Position-based indexing**         |
| Input          | Row/column **names (labels)**   | Row/column **integer positions**    |
| Slice behavior | **Inclusive** (end is included) | **Exclusive** (end is not included) |
| Example        | `df.loc[0:5, 'Price']`          | `df.iloc[0:5, 2]`                   |

Use iloc[] when you don’t know column names or want to select data based on position.
Example : df.iloc[:, 0:3]
Why iloc[] here?
- Suppose your dataset has unknown or messy column names
  Or column names may change dynamically
- Using positions (like first 3 columns) is safer and more consistent.
Use loc[] → when working with labels (names)
Use iloc[] → when working with positions (index numbers)